### ISSUE TITLE
Recommendation against using Pushy in a container environment 

### ISSUE THREAD

**Issue by matzew** [relayrides/pushy#134]
Hi,

I had a chat with @normanmaurer regarding the section `We recommend against using Pushy in a container environment....` section:
https://github.com/relayrides/pushy/blob/master/README.md#limitations-and-known-issues

@normanmaurer says the issues have been fixed, hence I am wondering if that section should be removed

**Comment by matzew** [comment]
@jchambers should the current recommendation be change, or removed? I think according to @normanmaurer and others, looks like the is gone

**Comment by jchambers** [comment]
@matzew Please see the exchange toward the bottom of https://github.com/netty/netty/issues/2522. It seems like, even using the best tools Netty offers, we're still not actually solving the problem for our users. Do you believe something has changed in recent Netty releases?

I'll admit I got discouraged by the problem and haven't really spent a lot of time on it since. I remain open to suggestions.

**Comment by jchambers** [comment]
Closing this in the absence of new developments. It appears that we're still limited by upstream issues.
