### ISSUE TITLE
Unable to import Netty on Eclipse (Newbie here)

### ISSUE THREAD

**Issue by shallsaur** [relayrides/pushy#145]
Hi,

I'm new to Pushy and I am trying to replace Javapns with your library.

I'm using Eclipse to work on it but I'm getting the following error.
<code>The type io.netty.channel.nio.NioEventLoopGroup cannot be resolved. It is indirectly referenced from required .class files</code>
It seems that it is unable to find Netty despite me adding it to my Referenced Libraries/Build Path.

My apologies if this is a stupid question as I am new to this. Hope I can get some pointers on this. Thank you.

**Comment by sunng87** [comment]
Because You don't have pushy's dependencies in your classpath. You may need to install maven plugin for Eclipse and add Pushy as a maven dependency, then maven will download all dependencies for you.

**Comment by jchambers** [comment]
@sunng87 I'm not so sure; isn't one of Netty's (minor) selling points that it has no dependencies?

@shallsaur My best guess is that you may have grabbed the wrong Netty jar. You'll want the all-in-one jar that comes with the Netty distribution if you're managing dependencies on your own. Since this isn't a bug report or feature request, I'm going to close this issue. May I ask that you move this conversation to the [mailing list](https://groups.google.com/d/forum/pushy-apns) if you still have questions?
