### ISSUE TITLE
Intermittent flush issues while sending notifications

### ISSUE THREAD

**Issue by lakshsubra** [relayrides/pushy#201]
Setup/Configuration: Pushy 0.4.3 using Netty 4.0.30. Vanilla/default pushy configuration.

Symptoms: Two commonly noticed symptoms...

 - pushy successfully writes the notification to netty channels - TRACE level logging has the following
       2015-10-13 02:19:24,200 TRACE [nioEventLoopGroup-2-2] com.relayrides.pushy.apns.ApnsConnection:550 - APNsPushManager-connection-2 successfully wrote notification 1. 
     Sometimes, the notification get delivered but the data/bytes corresponding to this notification remains in the send-Q. tcpdump shows that the data in the socket is being repeatedly retransmitted. After the maximum configured retries the connection is dropped. If another notification is sent while the retries are going on they get buffered and lost when the connection is dropped.

- pushy successfully writes the notification to netty. But the notification is not sent/received. Sending more notifications queues it up. Triggering pushy shutdown (by stopping the application) causes all the notifications to be sent and delivered.

**Comment by jchambers** [comment]
First, please accept my sincere apologies for the delayed reply! Thanks very much for the report. I'm hoping this issue is gone now that we've moved to the HTTP/2-based APNs protocol. Please leave a comment here if you see this problem come up again after updating Pushy and I'll reopen this issue.

Thanks again!
