### ISSUE TITLE
cant find incremental indexing

### ISSUE THREAD

**Issue by attasiva** [relayrides/pushy#227]
Hi, thanks for the nice work.. it is really helpful. however i have noticed that no incremental indexing is there as per apple documentation. i'm not sure how to add that support.. had a look at netty library but cant find a way.

as per apple documentation:

> The apns-id and apns-expiration headers should be encoded differently depending on initial or subsequent POST operation, as follows:
>
> - The first time you send these headers, encode them with incremental indexing to allow the header names to be added to the dynamic table
> - Subsequent times you send these headers, encode them as literal header fields without indexing

Thanks,
Siva.

**Comment by jchambers** [comment]
We left it out because it appears to be more of an optimization than a requirement and because, as you point out, it's not really obvious how we would exercise that level of direct control over header encoding without writing our own HPACK implementation.

At the same time, I should be clear that I don't know much about HPACK at all and have not really done much research, and it's possible that what the APNs docs are asking for is Just How HPACK Works Anyhow™. We'll give it some more attention in the future.

In the meantime, why do you ask? Have we made a bad assumption about the importance of incremental indexing?

**Comment by attasiva** [comment]
Thanks for your prompt reply and sorry for getting late.

I am also not sure if HPACK does that way or not.. and I am not sure how strict APNS is about this. did you test this library already for some actual push notification on an iphone?

**Comment by jchambers** [comment]
> did you test this library already for some actual push notification on an iphone?

Yes. We believe that Pushy 0.5 has been used to send millions of push notifications to date. As a rule, we don't release software we haven't tested.

**Comment by attasiva** [comment]
Thanks a lot :).

**Comment by jchambers** [comment]
Having read through Netty's source code around HTTP/2 headers, I'm confident that we're already encoding headers in such a way that the size of the dynamic table will be kept to a minimum.
