### ISSUE TITLE
Release with Proxy Feature

### ISSUE THREAD

**Issue by teknex** [relayrides/pushy#250]
Please make a release available on Maven Central with the new proxy feature.

Thank you

Philip

**Comment by jchambers** [comment]
Proxy support is scheduled to go out as part of Pushy v0.6. Please see the [v0.6 milestone](https://github.com/relayrides/pushy/milestones/v0.6) for progress on that release. Please feel free to build Pushy from source in the meantime.

Since this is neither a new feature request (we've already built proxy support) nor a bug report, the [mailing list](https://groups.google.com/d/forum/pushy-apns) is probably the best place to continue the discussion if you have more questions.
