### ISSUE TITLE
HTTP2 connections

### ISSUE THREAD

**Issue by matzew** [relayrides/pushy#254]
Hi @jchambers 

from the wiki:

> Pushy 0.5 and newer, which use Apple's HTTP/2-based APNs protocol, do not need to maintain parallel connections in quite the same way.

I have a question:
* Is there no requirement anymore regarding (15?) concurrent/parallel connections to APNs ?

**Comment by jchambers** [comment]
> Is there no requirement anymore regarding (15?) concurrent/parallel connections to APNs?

I don't mean to be difficult, but I'm not sure exactly what you mean; I don't think that was ever really a requirement. Having a couple concurrent connections was important in the old days because it was expected that connections would open and close frequently (i.e. every time the APNs server rejected a notification for any reason). With a single connection, things would grind to a halt if that connection closed. That wouldn't be the end of the world; it would just slow things down a bit.

Connection closure under the HTTP/2-based protocol should be quite rare (the connection stays open when a notification is rejected), and so the need to have a bunch of parallel connections is greatly reduced. So if it was a best practice—if not a requirement—to have parallel connections in the old days, it's much less so now.

One thing to note is that there *might* be some performance gains to be had with multiple concurrent `ApnsClient` instances, since each client will only ever use a single thread. If you think you're CPU-bound, having multiple parallel clients might allow you to use more threads (and CPU cores). Still, I think that's a bit off into the weeds for most users.

Does that answer your question? I'm worried that I'm misunderstanding what you're getting at.

**Comment by vargusz** [comment]
With the old APNs protocol, there used to be a belief about Apple disallowing more than 15 concurrent connections per source/topic. That limit was never really documented in Apple's docs. Experience showed no penalties, however.

**Comment by jchambers** [comment]
Hey, @matzew, I'm going to close this for now. If you need more information or feel that the question hasn't been answered adequately, please leave a comment and we'll reopen the issue.

Thanks!

**Comment by matzew** [comment]
:+1:

On Wed, Mar 30, 2016 at 4:48 AM, Jon Chambers <notifications@github.com>
wrote:

> Closed #254 <https://github.com/relayrides/pushy/issues/254>.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/relayrides/pushy/issues/254#event-607632361>
>



-- 
Matthias Wessendorf

blog: http://matthiaswessendorf.wordpress.com/
sessions: http://www.slideshare.net/mwessendorf
twitter: http://twitter.com/mwessendorf
