### ISSUE TITLE
Appropriate integration with alpn-boot with gradle?

### ISSUE THREAD

**Issue by mbalex99** [relayrides/pushy#262]
Hi everyone, 

I heard this is the best push client for apple apps. 
However, I'm seriously struggling on integrating alpn-boot with a gradle project. Has anyone had any luck? I've specified it to be a runtime dependency but it doesn't look like it's working.

Any suggestions or directions would be much appreciated.

**Comment by jchambers** [comment]
@mbalex99 This comes up pretty frequently, which I think means it's time for me to add it to [the FAQ](https://github.com/relayrides/pushy/wiki/Frequently-asked-questions). There are two things to bear in mind here:

1. You need to add `alpn-boot` to your *boot classpath*, not your normal classpath. There *is* a difference, and in this case, it's really important.
2. Unless you're actually running your application via gradle, gradle alone will not solve this problem for you. Gradle will happily add libraries to the classpath, but will not add them to the *boot classpath* without additional intervention. You'll need to pass additional arguments to your application when you run it so it will use `alpn-boot`.

Here's an example:

```
java -Xbootclasspath/p:/Users/jon/.m2/repository/org/mortbay/jetty/alpn/alpn-boot/8.1.6.v20151105/alpn-boot-8.1.6.v20151105.jar -jar my-app.jar
```

Also, since this isn't really a bug report or a feature request, the [mailing list](https://groups.google.com/d/forum/pushy-apns) is probably a better home for this conversation. I'm going to close this issue for now, but please do start a thread on the mailing list if you need more help!
