### ISSUE TITLE
When I off the internet connection of mobile, then send the push. After it, I on the internet connection. I didn't receive any push.

### ISSUE THREAD

**Issue by SamitaMShephertz** [relayrides/pushy#263]

**Comment by SamitaMShephertz** [comment]
final ApnsClient<SimpleApnsPushNotification> apnsClient = new ApnsClient<>(
                new File("C://Users//Ajay//Downloads//iphone_dev.p12"), "1234");

        final Future<Void> connectFuture = apnsClient.connect(ApnsClient.DEVELOPMENT_APNS_HOST);
        connectFuture.await();

        // Once we're connected, we can start sending push notifications.
        final SimpleApnsPushNotification pushNotification;

        {
            final ApnsPayloadBuilder payloadBuilder = new ApnsPayloadBuilder();
            payloadBuilder.setAlertBody("Example!");

            final String payload = payloadBuilder.buildWithDefaultMaximumLength();
            final String token = TokenUtil.sanitizeTokenString("yyyyyyyyyyyyyyyyyyyyyy");

            pushNotification = new SimpleApnsPushNotification(token, "com.example.myApp", payload);
        }

        
        final Future<PushNotificationResponse<SimpleApnsPushNotification>> sendNotificationFuture =
                apnsClient.sendNotification(pushNotification);

        try {
            final PushNotificationResponse<SimpleApnsPushNotification> pushNotificationReponse =
                    sendNotificationFuture.get();
            if (pushNotificationReponse.isAccepted()) {
            	System.out.println("Message Send Sucessfully");
                // Everything worked! The notification was successfully sent to
                // and accepted by the gateway.
            } else {
                // Something went wrong; this should be considered a permanent
                // failure, and we shouldn't try to send the notification again.
                System.out.println("Notification rejected by the APNs gateway: " +
                        pushNotificationReponse.getRejectionReason());

                if (pushNotificationReponse.getTokenInvalidationTimestamp() != null) {
                    // If we have an invalidation timestamp, we should also stop
                    // trying to send notifications to the destination token (unless
                    // it's been renewed somehow since the expiration timestamp).
                }
            }
        } catch (final ExecutionException e) {
         
            System.err.println("Failed to send push notification.");
            e.printStackTrace();

            if (e.getCause() instanceof ClientNotConnectedException) {
               
                apnsClient.getReconnectionFuture().await();
            }
        }
        final Future<Void> disconnectFuture = apnsClient.disconnect();
        disconnectFuture.await();

**Comment by SamitaMShephertz** [comment]
Result is - 
[nioEventLoopGroup-2-1] INFO com.app42.push.apns.ApnsClient - Connected to api.development.push.apple.com/17.172.238.203:443.
com.app42.push.apns.ApnsClient - Disconnecting.
Message Send Sucessfully

But I didnt get notification on mobile

**Comment by jchambers** [comment]
If the notification was accepted by the gateway, I'm not sure why it wouldn't have appeared on the destination device. I'd encourage you to take a look at this [tech note from Apple](https://developer.apple.com/library/ios/technotes/tn2265/_index.html), though, and particularly the parts about enabling push notification logging on your phone.

That said, it sounds like Pushy itself is doing its job as expected: it's sending notifications to the APNs server and reporting the server's reply. Since this does not appear to be a bug with Pushy itself, I'm going to close this issue.

If you need help for things other than bugs or feature requests, I'd encourage you to try the [mailing list](https://groups.google.com/d/forum/pushy-apns), which is much better suited for general support questions.

Cheers!
