### ISSUE TITLE
pushy seems like has no feedback component?

### ISSUE THREAD

**Issue by yaogdu** [relayrides/pushy#299]

**Comment by jchambers** [comment]
As of v0.5, Pushy uses the new HTTP/2-based APNs protocol, which does not have a feedback component. Instead, the APNs server tells us immediately if a notification could not be delivered because the token has expired. Please see the [`PushNotificationResponse` documentation](http://relayrides.github.io/pushy/apidocs/0.7/com/relayrides/pushy/apns/PushNotificationResponse.html) for details.

**Comment by yaogdu** [comment]
@jchambers got it.  thanks so much
