### ISSUE TITLE
Add support for Token Authentication

### ISSUE THREAD

**Issue by fabiankoebel** [relayrides/pushy#314]
see WWDC 2016: [https://developer.apple.com/videos/play/wwdc2016/724/](https://developer.apple.com/videos/play/wwdc2016/724/)

**Comment by jchambers** [comment]
Sounds like this should cut down on Certificate Woes™ pretty significantly, and will be especially helpful for users working with multiple topics; my understanding is that, since we're authenticating once per request and not once per connection, a single client will be able to work with multiple signing keys/topics.

Some notes from the WWDC video (since there are some details in audio that aren't really clear from the slides):

- We'll send an auth token with every request
  - It stands to reason, but would like to confirm that this means that a single connection (if "armed" with multiple signing keys) can work with multiple topics
- Uses [JSON Web Tokens](https://jwt.io/) to generate auth tokens
  - Algorithm is `ES256`
  - `iss` is the developer team ID (I'm not 100% sure I know what this means, but I believe it's the ten-character alphanumerical ID)
  - `iat` is the timestamp, in *seconds* since the epoch, at which the token was issued
- Tokens will be sent in an HTTP/2 header like this: `authorization = bearer token.string.here`
- New error codes when using tokens
  - `InvalidProviderToken` is fatal and comes with an `HTTP/403` status code
  - `ExpiredProviderToken` is non-fatal (the token needs to be regenerated) and also comes with an `HTTP/403` status
- Tokens expire after an hour

This is supposed to happen "later this year." As a point of comparison, APNs via HTTP/2 was announced at WWDC 2015 with an expected deadline of "later this summer" for a draft of the updated spec and "later this year" for release to production. In the end, both things happened on December 17, 2015. I recognize that the transition to HTTP/2 was probably a bigger deal than a transition to auth tokens, but I think we should be cautious about betting too heavily on any particular timeline. Looking forward to this, though!

**Comment by jchambers** [comment]
Also, while gathering notes, it sounds like OpenJDK users may need to [jump through some hoops](http://armoredbarista.blogspot.com/2013/10/how-to-use-ecc-with-openjdk.html) to be able to use `SHA256withECDSA`.

**Comment by jchambers** [comment]
I've opened a work-in-progress pull request; see #319 to monitor our progress on token authentication.

**Comment by jchambers** [comment]
Looks like upstream support for token authentication has been [released](https://developer.apple.com/news/?id=09222016a). I'll be on vacation all next week, but will hope to polish off #319 when I get back.

**Comment by EdwinRikkers** [comment]
+1 what is the status on this one?

**Comment by jchambers** [comment]
As mentioned in the previous content, I've just returned from vacation and hope to finish #319 shortly.

**Comment by jchambers** [comment]
A poll for the audience: when we go to token-based authentication, will you still need the older TLS-based authentication? Removing TLS-based auth will make things a lot simpler, but I also recognize that other folks may still depend on it.

Thanks!

**Comment by jmason** [comment]
yep, we definitely will I'm afraid ;)

**Comment by gabek** [comment]
I'd be happy to completely move over to tokens.

**Comment by EdwinRikkers** [comment]
We would be happy to to completely go to tokens... but understand if people still need the older TLS-based.

**Comment by ksquaredkey** [comment]
I tend to be cautious and the sort of person who would normally ask for the backwards compatibility.  However, the nature of the APNS Tokens and the pain I've had with folks tracking cert expiration makes me very willing to take a change with no backwards compatibility.  If there is a need for the old form, folks can use the older version of the library.  If there are fixes needed to the older version, folks can fork off and create a new maintenance project.

**Comment by secolaha** [comment]
Hi, we have a system with multiple apps that are developed by different customers.

Keeping both means you can migrate you customers slowly instead of having to make sure everyone updates at the same time.

 

So if possible I would prefer to have both but have the TLS stuff deprecated so we know how long we have to migrate the apps.

Regards, 

/Lars

**Comment by vader** [comment]
Am I mistaken in thinking we have to go 100% tokens? 
My certificate expired and I push via AWS Simple Notification Service which requires a .p12 cert. I can not see anyway for apple to issue me anything other than token auth so what's the point of keeping both? 
Please tell me I am wrong and apple will keep backward cert auth so I can keep sending notifications while a develop a hack to send token based which I will have to do via NodeJS at the moment.

**Comment by petrdvorak** [comment]
@vader Apple keeps backward compatibility for push notifications - you can even still use the old binary interface they have back then. But IMO using tokens is the way to go and I would be happy to see the certificate support dropped in the latest Pushy version.

**Comment by petrdvorak** [comment]
@jchambers People who need certificate based auth can still use older version of your library... right? ;-)

**Comment by EdwinRikkers** [comment]
@jchambers when will this be released ?

**Comment by vader** [comment]
I am really sorry for my misinformation. Apple have left backward compatibility I just in panic of my notifications not working could only see the token based authentication. 
Personally I can't wait to move to tokens these yearly expiring certificates are driving me nuts.

**Comment by petrdvorak** [comment]
Hello @jchambers, could you please provide some hint about timing of the release? I currently stopped working on one of my projects to wait for this to be implemented - I would like to avoid writing a new software built on top of old technology. But at the same time, I would like to have some time estimates for the client.

Btw - where do I pay for this software? :) It saves me time and seems to be too well maintained to be provided for free with no commercial options.

**Comment by jchambers** [comment]
Thanks for the feedback, everybody. It sounds like there are enough users that are dealing with third-party certificates that we should have at least one transitional release that support both mutual TLS authentication and token-based authentication, though my hope is to move away from that situation quickly.

For those of you asking about a release date, please accept my sincere thanks for your excitement and interest. Releasing a new version of Pushy with token-based authentication is a priority, but it is not our only priority right now. I can't commit to a specific date. On the brighter side, please do bear in mind that we have a mostly-complete implementation in #319, and please also note that we're soliciting feedback about final integration concerns right now.

**Comment by EdwinRikkers** [comment]
What's the status on this one? Really eager to implement this in our software!

**Comment by jchambers** [comment]
I've closed #319 in favor of #397, which is pretty much the same thing, except it preserves support for TLS-based client authentication.

**Comment by jchambers** [comment]
I've merged #397 and am planning to put out a release later tonight.
