### ISSUE TITLE
Too complex to use with tomcat

### ISSUE THREAD

**Issue by TimYi** [relayrides/pushy#318]
I tried pushy in normal java project, it works well.
But when I deploy it to tomcat, tcnative conflicts with tomcat. And netty-boot is too complex to use.
Tomcat local library has a tomcat-jni.jar which use the same namespace with tcnative. Tomcat's classloader will also cause some problem.
So far, I have no idea about how to use pushy within tomcat container.

**Comment by jchambers** [comment]
> And netty-boot is too complex to use.

I don't mean to nit-pick, but do you mean alpn-boot rather than netty-boot?

Regrettably, alpn-boot and netty-tcnative are our only options right now, and there isn't much we can do from the Pushy side of things to improve the situation. The Tomcat/netty-tcnative conflict is a [known issue](https://github.com/netty/netty-tcnative/issues/136). I would like to point out that if you use Tomcat without native extensions, there will be no conflict with netty-tcnative, though I recognize that's not a great option, either.

While I certainly acknowledge your concerns, I think it makes sense to close this issue because:

- Even though it may be complicated, alpn-boot *will* get the job done, so there is a viable way to use Pushy inside a Tomcat container.
- There isn't really any meaningful way for us to improve the situation beyond waiting for an upstream fix.

If you feel there's more specific action we can take, please post a comment here and we'll revisit the issue.
