### ISSUE TITLE
Error: ALPN unsupported. How to setup pushy with gradle?

### ISSUE THREAD

**Issue by CyrusNG** [relayrides/pushy#328]
I try to use pushy with gradle instead of maven as following:
	compile('com.relayrides:pushy:0.7.3')
But I got error when I call APNs server.
        java.lang.ClassNotFoundException: org.eclipse.jetty.alpn.ALPN$Provider

Then I add:
       	compile('org.mortbay.jetty.alpn:alpn-boot:7.1.3.v20150130')
But another error shown when I call APNs server.
        java.lang.RuntimeException: ALPN unsupported. Is your classpatch configured correctly? See http://www.eclipse.org/jetty/documentation/current/alpn-chapter.html#alpn-starting

And, how can I set classpatch in gradle?

**Comment by CyrusNG** [comment]
So I add one variable in Eclipse's Default VM arguments:
-Xbootclasspath/p:/Users/<XXX>/alpn-boot-7.1.3.v20150130.jar

then another issue happen:
javax.net.ssl.SSLHandshakeException: No appropriate protocol (protocol is disabled or cipher suites are inappropriate)

Is there anyone has idea on this?

**Comment by jchambers** [comment]
This appears to be a request for general support rather than a bug report or feature request. We generally ask people to keep these discussions on [the mailing list](https://groups.google.com/d/forum/pushy-apns) because:

1. More people are available on the mailing list to help you.
2. The answer to this kind of question is likely to be useful to other people, and having the conversation on the mailing list makes it easier for others to discover the answer.
3. We can't reasonably solve your problem by making changes in code.

That said, the `SSLHandshakeException` is most likely happening because your JDK doesn't support the ciphers required for HTTP/2. You'll need to use an alternative cryptographic provider, a different JDK, or (as we usually recommend) a native SSL provider.

Again, because this is neither a bug nor a feature request, I'm going to close this issue. Please don't hesitate to continue the conversation on the mailing list, though!
