### ISSUE TITLE
java.lang.ClassNotFoundException: org.eclipse.jetty.alpn.ALPN$Provider

### ISSUE THREAD

**Issue by UncleDrewZhu** [relayrides/pushy#333]
Use spring-boot project push notification. Message can be sent by own test case in project,but when i use http request to visit my spring-boot project, there is java.lang.ClassNotFoundException: org.eclipse.jetty.alpn.ALPN$Provider.Anyone has the same problem may help me? Thanks in advance

**Comment by jchambers** [comment]
Hello!

This sounds more like a request for general support than it does like a bug report or a feature request. We generally ask people to move these kinds of questions to [the Pushy mailing list](https://groups.google.com/d/forum/pushy-apns) because:

1. The mailing list has a wider audience, and you're more likely to find somebody who has experience with your particular circumstances on the mailing list.
2. Posting your question to the mailing list can help other people who are having the same problem.
3. Because there isn't a bug to fix or a feature to add, we can't reasonably solve your problem by making any kind of engineering change.

I emphasize that we'd be happy to help, but let's move this conversation to a different venue. In the meantime, it sounds like you're missing the `alpn-api` dependency.
