### ISSUE TITLE
support for feedback service for inactive devices

### ISSUE THREAD

**Issue by svajdlenka** [relayrides/pushy#344]
Hi, I am newbie to GitHub, I don't know where to ask questions. Is there any support for Feedback service for inactive devices in your library? Thank you.

**Comment by jchambers** [comment]
> Is there any support for Feedback service for inactive devices in your library?

Not any more. Pushy uses the HTTP/2-based APNs API, which no longer has a feedback service. Using the new API, the APNs server will just tell us immediately if a notification couldn't be delivered because the token was expired. Please see the [`PushNotificationResponse` docs](http://relayrides.github.io/pushy/apidocs/0.7/com/relayrides/pushy/apns/PushNotificationResponse.html) for details.

**Comment by qiankunli** [comment]
but,If you send invalid token more than a certain amount, the  apn server will close the connection. it will slow down the speed of push system, how to do?

**Comment by jchambers** [comment]
I'm sorry—I don't understand the question. Could you please rephrase?
