### ISSUE TITLE
Is the Topic name really required for creating SimpleApnsPushNotification object in order to deliver the PushNotification?

### ISSUE THREAD

**Issue by jai-v** [relayrides/pushy#348]
I am building an application where the user should be able to send a push notification by uploading the .p12 file and providing the pass phrase.
As the topic name is already present in the subject line of .p12 file, the push notification should be still delivered if I pass the topic name as null while creating the SimpleApnsPushNotification Object.

Also, is there any function which could read all the topic names present inside the certificate (.p12 file) ?

**Comment by jchambers** [comment]
I believe what you're asking for is essentially what #323 was suggesting. In short, we are deliberately opting out of this feature because the APNs protocol will be moving away from certificates and toward bare private keys in the near future, and we don't want to build dependence on a feature that we know is going away.

> Also, is there any function which could read all the topic names present inside the certificate (.p12 file) ?

Please see [`TopicUtil#extractApnsTopicsFromCertificate(Certificate)`](https://github.com/relayrides/pushy/blob/v0.7.3/pushy/src/test/java/com/relayrides/pushy/apns/TopicUtil.java#L17) if you'd like an example, but please also note that `TopicUtil` has been removed entirely in v0.8.

I'm going to close this for now (since I think it's already been covered in #323), but please post a comment here if you think we're misunderstanding the issue and we'll revisit. Thanks!

**Comment by jai-v** [comment]
Thank you for the feedback. I really appreciate your quick reply..
