### ISSUE TITLE
Use Certificate from Keystore?

### ISSUE THREAD

**Issue by mike-koch** [relayrides/pushy#354]
Is it possible to use pushy with certificates stored in a keystore, rather than passing in a file path and having the password stored in source control?  The Tomcat container I'm using for this project has a keystore already in place and is working with other services; however it appears I am forced to provide a file path and password for the `ApnsClient`.

**Comment by jchambers** [comment]
Hello!

This sounds more like a request for general support than it does like a bug report or a feature request. We generally ask people to move these kinds of questions to [the Pushy mailing list](https://groups.google.com/d/forum/pushy-apns) because:

1. The mailing list has a wider audience, and you're more likely to find somebody who has experience with your particular circumstances on the mailing list.
2. Posting your question to the mailing list can help other people who are having the same problem.
3. Because there isn't a bug to fix or a feature to add, we can't reasonably solve your problem by making any kind of engineering change.

I emphasize that we'd be happy to help, but let's move this conversation to a different venue. In the meantime, the `ApnsClient` class has a number of [constructors that accept credentials in other formats](http://relayrides.github.io/pushy/apidocs/0.7/com/relayrides/pushy/apns/ApnsClient.html). If you're working with a `KeyStore`, you'll need to do some work on your own to extract an `X509Certificate` and `PrivateKey` from the `KeyStore`.
