### ISSUE TITLE
Remove .gitignore file from resulting jar artifacts.

### ISSUE THREAD

**Issue by dant3** [relayrides/pushy#355]
For some reason currently artifacts for 0.7.3 release contains `.gitignore` file inside of it's jar. It shouldn't be there.

**Comment by jchambers** [comment]
Ohhhhhhhh… I think I know what happened here. I used the "add an empty `.gitignore` file so git knows to create an empty directory" in the various `resources` directories. Unfortunately, Maven now thinks that those `.gitignore` files are, themselves, useful resources to be included in the jar.

This is fixed in #360.

**Comment by dant3** [comment]
Thanks! Looking forward for 0.8 release
