### ISSUE TITLE
Question about using Pushy in multi-tenant environment

### ISSUE THREAD

**Issue by sachinwalia2k8** [relayrides/pushy#374]
Do you have any suggestions / recommendations If we are using pushy in multi-tenant environment whereby IOS certs are added or removed dynamically:

```
final ApnsClient apnsClient = new ApnsClientBuilder()
        .setClientCredentials(new File("/path/to/certificate.p12"), "p12-file-password")
        .build();

```
Can we create apnsClient on demand whenever request comes to send notification. Is it an expensive step?

Also the one below. Do you recommend opening connection once in the lifetime of the web application and close it once application is closed?

```
final Future<Void> connectFuture = apnsClient.connect(ApnsClient.DEVELOPMENT_APNS_HOST);
connectFuture.await(); 

```

I am using Spring Boot and would appreciate any sugestions in terms of best practices for using Pushy in a multi-tenant microservice environment.

**Comment by jchambers** [comment]
Hello!

This sounds more like a request for general support than it does like a bug report or a feature request. We generally ask people to move these kinds of questions to [the Pushy mailing list](https://groups.google.com/d/forum/pushy-apns) because:

1. The mailing list has a wider audience, and you're more likely to find somebody who has experience with your particular circumstances on the mailing list.
2. Posting your question to the mailing list can help other people who are having the same problem.
3. Because there isn't a bug to fix or a feature to add, we can't reasonably solve your problem by making any kind of engineering change.

I emphasize that we'd be happy to help, but let's move this conversation to a different venue.
