### ISSUE TITLE
The Performance of Pushy

### ISSUE THREAD

**Issue by ScienJus** [relayrides/pushy#376]
when i use pushy，i used netty future and Listener to log every request time，like：

```
long start = System.currentTimeMillis();
client.sendNotification(new SimpleApnsPushNotification(token, "xxxx", payload))
    .addListener(future -> {
      try {
        PushNotificationResponse<SimpleApnsPushNotification> result = (PushNotificationResponse<SimpleApnsPushNotification>) future.get();
        long end = System.currentTimeMillis();
        System.out.println((end - start) + "ms");
      } catch (ExecutionException e) {
        if (e.getCause() instanceof ClientNotConnectedException) {
          client.getReconnectionFuture().await();
          push(token, payload);
        }
        throw new RuntimeException(e);
      }
    });
```

but i found that all of request time is bigger than `300ms`. it is unacceptably low performance. i don't know it's my code fault or it's real Pushy and APNs server's Performance，can you help me?

**Comment by jchambers** [comment]
I think we need some more information. First, and probably most importantly, are you using `netty-tcnative` or are you using Jetty's `alpn-boot`/`alpn-agent` approach? Do you see elevated CPU usage during those 300ms? What happens if you try to send 100 notifications instead of just one (i.e. could we just be seeing a lot of startup time on the first notification)?

**Comment by ScienJus** [comment]
Thank you for the comment. i used `netty-tcnative`. i sent 100-200 notifications in a test and they are all bigger than 300ms(single threading model). can you tell me the number in your case?

**Comment by ScienJus** [comment]
@jchambers and do you have any idea how to test the network with apns server?

**Comment by ScienJus** [comment]
ant this is my DropwizardApnsClientMetricsListener's report:

```
-- Meters ----------------------------------------------------------------------
MyApnsClient.acceptedNotifications
             count = 0
         mean rate = 0.00 events/second
     1-minute rate = 0.00 events/second
     5-minute rate = 0.00 events/second
    15-minute rate = 0.00 events/second
MyApnsClient.connectionFailures
             count = 0
         mean rate = 0.00 events/second
     1-minute rate = 0.00 events/second
     5-minute rate = 0.00 events/second
    15-minute rate = 0.00 events/second
MyApnsClient.rejectedNotifications
             count = 62
         mean rate = 1.95 events/second
     1-minute rate = 0.80 events/second
     5-minute rate = 0.18 events/second
    15-minute rate = 0.06 events/second
MyApnsClient.sentNotifications
             count = 63
         mean rate = 1.98 events/second
     1-minute rate = 0.81 events/second
     5-minute rate = 0.19 events/second
    15-minute rate = 0.06 events/second
MyApnsClient.writeFailures
             count = 0
         mean rate = 0.00 events/second
     1-minute rate = 0.00 events/second
     5-minute rate = 0.00 events/second
    15-minute rate = 0.00 events/second

-- Timers ----------------------------------------------------------------------
MyApnsClient.connectionTimer
             count = 1
         mean rate = 0.03 calls/second
     1-minute rate = 0.01 calls/second
     5-minute rate = 0.00 calls/second
    15-minute rate = 0.00 calls/second
               min = 2575.78 milliseconds
               max = 2575.78 milliseconds
              mean = 2575.78 milliseconds
            stddev = 0.00 milliseconds
            median = 2575.78 milliseconds
              75% <= 2575.78 milliseconds
              95% <= 2575.78 milliseconds
              98% <= 2575.78 milliseconds
              99% <= 2575.78 milliseconds
            99.9% <= 2575.78 milliseconds
MyApnsClient.notificationTimer
             count = 62
         mean rate = 1.95 calls/second
     1-minute rate = 0.80 calls/second
     5-minute rate = 0.18 calls/second
    15-minute rate = 0.06 calls/second
               min = 280.06 milliseconds
               max = 2079.45 milliseconds
              mean = 405.32 milliseconds
            stddev = 276.64 milliseconds
            median = 307.98 milliseconds
              75% <= 405.99 milliseconds
              95% <= 1123.90 milliseconds
              98% <= 1298.18 milliseconds
              99% <= 2079.45 milliseconds
            99.9% <= 2079.45 milliseconds
```

**Comment by ScienJus** [comment]
sorry, my bad, just because i am in China, when i run the code in my server which in New Jersey. it's just 50ms every request.

**Comment by jchambers** [comment]
> when i run the code in my server which in New Jersey. it's just 50ms every request.

Well, that's disappointing :\

Still! This is a good opportunity to clarify that you *do not* need to wait for a reply to one notification before sending the next. In situations where you have plenty of bandwidth, but high latency (which appears to be the case here), sending notifications in parallel and using listeners (instead of `Future#get()` or `Future#await()`) will *dramatically* increase your throughput. It's the difference between this:

```
|-- 300ms -- | |-- 300ms -- | |-- 300ms -- | |-- 300ms -- | |-- 300ms -- |
```

…and this:

```
|-- 300ms -- |
 |-- 300ms -- |
  |-- 300ms -- |
   |-- 300ms -- |
    |-- 300ms -- |
```

Note that both approaches are still just using one thread even though the latter approach has multiple notifications "in flight" at the same time.

 For an example of sending notifications with this strategy, please see the [`ApnsClient` benchmark](https://github.com/relayrides/pushy/blob/master/benchmark/src/main/java/com/relayrides/pushy/apns/ApnsClientBenchmark.java#L98-L108).

In any case, it sounds like Pushy is doing its job as expected, and there's regrettably little we can do about Apple's decisions about where to locate their servers. I'm going to close this issue for now, but please let us know if something still seems to be amiss.

**Comment by ShanAmos** [comment]
can you tell me how to use DropwizardApnsClientMetricsListener in my code, if any example is available will be better. Thank u very much

**Comment by ShanAmos** [comment]
can you tell me how to use DropwizardApnsClientMetricsListener in my code, if any example is available will be better. Thank u very much

**Comment by ShanAmos** [comment]
can you tell me how to use DropwizardApnsClientMetricsListener in my code, if any example is available will be better. Thank u very much

**Comment by ShanAmos** [comment]
can you tell me how to use DropwizardApnsClientMetricsListener in my code, if any example is available will be better. Thank u very much

**Comment by ShanAmos** [comment]
can you tell me how to use DropwizardApnsClientMetricsListener in my code, if any example is available will be better. Thank u very much

**Comment by ShanAmos** [comment]
can you tell me how to use DropwizardApnsClientMetricsListener in my code, if any example is available will be better. Thank u very much

**Comment by ShanAmos** [comment]
can you tell me how to use DropwizardApnsClientMetricsListener in my code, if any example is available will be better. Thank u very much

**Comment by jchambers** [comment]
Please see the [README](https://github.com/relayrides/pushy/tree/master/dropwizard-metrics-listener).
