### ISSUE TITLE
Question about HTTP/2 response from Apple

### ISSUE THREAD

**Issue by badgersow** [relayrides/pushy#380]
Hi, guys.

Could you please clarify one case?
Apple documentation [here](https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/APNSOverview.html#//apple_ref/doc/uid/TP40008194-CH8-SW1) states the following

```
In the certificate-based trust scheme, there is 
1) no per-push validation performed, and 
2) no HTTP/2 response available to you for each notification push request.
```

But if this is true, I don't understand how we get `PushNotificationResponse` with `rejectionReason` in pushy.
Is the apple documentation wrong? Or we do not use certificate-based trust scheme?

Thanks for your time

**Comment by jchambers** [comment]
Hello!

This sounds more like a request for general support than it does like a bug report or a feature request. We generally ask people to move these kinds of questions to [the Pushy mailing list](https://groups.google.com/d/forum/pushy-apns) because:

1. The mailing list has a wider audience, and you're more likely to find somebody who has experience with your particular circumstances on the mailing list.
2. Posting your question to the mailing list can help other people who are having the same problem.
3. Because there isn't a bug to fix or a feature to add, we can't reasonably solve your problem by making any kind of engineering change.

I emphasize that we'd be happy to help, but let's move this conversation to a different venue.

That said, we definitely still get HTTP/2 responses in "certificate mode." I suspect that's just poor wording on their part (maybe intended to mean that we don't get per-notification HTTP/2 responses *about authentication*).
