### ISSUE TITLE
Provide better alternative to current SSL implementation

### ISSUE THREAD

**Issue by blockmar** [relayrides/pushy#386]
The current SSL requirements using `netty-tcnative` and `alpn-api` with versions that change with every release of Java if very hard to maintain in an automatic build environment with maven versioning. Especially if development is done on a different platform (read OSX) than testing (read Linux)

**Comment by jchambers** [comment]
I believe you're confusing `netty-tcnative` and `alpn-boot`. Please note that the same version of `netty-tcnative` should work with a variety of JDK/JRE versions, and the [statically-linked variety](http://search.maven.org/#search%7Cga%7C1%7Ca%3A%22netty-tcnative-boringssl-static%22) should work across supported operating systems.

Speaking generally, we're using the best tools the Java ecosystem has to offer when it comes to ALPN. It is a developing field, and we'll adopt new technology as it becomes available. That said, in the absence of a concrete suggestion, I believe what you're asking for ("make ALPN better under Java") is well beyond the scope of Pushy.

I'm going to close this issue for now (since, to my knowledge, we're already using the best tools available). If you have a concrete suggestion you think we should pursue, please leave a comment here and we'll revisit the issue.

**Comment by blockmar** [comment]
Thanks for taking the time to give constructive feedback. Will have another look at using the statically linked library. Keep up the good work.
