### ISSUE TITLE
Exception while reading p12 file

### ISSUE THREAD

**Issue by vivekpatidar** [relayrides/pushy#389]
Hi, 

Here is our code to read p12 file :

`
final ApnsClient apnsClient = new ApnsClientBuilder().setClientCredentials(new File("/var/cert/pushcert.p12"), "passkey").build();
`

And we are getting following exception while reading p12 file.

```
java.io.IOException: toDerInputStream rejects tag type 66
	sun.security.util.DerValue.toDerInputStream(DerValue.java:847)
	sun.security.pkcs12.PKCS12KeyStore.engineLoad(PKCS12KeyStore.java:1883)
	java.security.KeyStore.load(KeyStore.java:1445)
	com.relayrides.pushy.apns.P12Util.getFirstPrivateKeyEntryFromP12InputStream(P12Util.java:40)
	com.relayrides.pushy.apns.ApnsClientBuilder.setClientCredentials(ApnsClientBuilder.java:137)
	com.relayrides.pushy.apns.ApnsClientBuilder.setClientCredentials(ApnsClientBuilder.java:111)
```

Please suggest us what's wrong with above code.

We are using pushy-0.8.1 version

Thanks...

**Comment by jchambers** [comment]
Hello!

This sounds more like a request for general support than it does like a bug report or a feature request. In this case, I suspect it's not a bug because it's a very central piece of code, and a bug would likely be affecting a very wide audience. We generally ask people to move these kinds of questions to [the Pushy mailing list](https://groups.google.com/d/forum/pushy-apns) because:

1. The mailing list has a wider audience, and you're more likely to find somebody who has experience with your particular circumstances on the mailing list.
2. Posting your question to the mailing list can help other people who are having the same problem.
3. Because there isn't a bug to fix or a feature to add, we can't reasonably solve your problem by making any kind of engineering change.

I emphasize that we'd be happy to help, but let's move this conversation to a different venue. In the meantime, it sounds like you either have a malformed .p12 file or are trying to read a PEM file as a .p12 file.
