### ISSUE TITLE
Back-pressure mechanism causes unexpected write exceptions

### ISSUE THREAD

**Issue by qiankunli** [relayrides/pushy#407]
there is a lot of "write failure" when sending a large amount of notifications. 

for ApnsClient class, responsePromises save the notifications that have not receive response, can you add a logic in sendNotification method：block sendNotification when the size of the responsePromises bigger than the threshhold(setting by user)。

**Comment by jchambers** [comment]
It sounds like you're asking us to roll back #383, which I'm beginning to think we may have implemented a bit hastily.

@stepheno I think one weakness with the current approach is that there's no way for callers to know when the problem (too much stuff in the write queue) has been resolved. I have two thoughts:

1. Just remove `ClientBusyException` entirely. Callers can increment a counter when they send a notification, then add a listener that decrements the counter when a notification is resolved. As near as I can tell, that would meet the same user need without creating quite so much of an imposition on callers who aren't worried about flooding.
2. Replace `ClientBusyException` with a listener interface callers can implement to learn about client writability changes.

Since the main goal for the next release is to implement connection pooling, my inclination is to take the former approach. @stepheno would that be disastrous for your use case?

**Comment by stepheno** [comment]
@jchambers I'm fine with the first approach. I can take a ticket/lease rate limiting semaphore approach in the interim. Looking forward to support for tokens and connection pooling :+1:

**Comment by jchambers** [comment]
> Looking forward to support for tokens and connection pooling

Sanity check: we [already released](https://github.com/relayrides/pushy/releases/tag/pushy-0.9) auth token support. Are you looking for something different?

**Comment by stepheno** [comment]
That's great news. I wasn't following that closely over the holidays, entirely missed the new release. Thanks for the heads up.

**Comment by jchambers** [comment]
This has been rolled back in 3f45633.
