### ISSUE TITLE
[Question] Push notifications for other providers

### ISSUE THREAD

**Issue by l3ender** [relayrides/pushy#409]
Am just curious, what libraries are others (Turo, etc) using for other PN providers, like GCM/FCM?

**Comment by jchambers** [comment]
Hello!

This sounds more like a general question than it does like a bug report or a feature request. We generally ask people to move these kinds of questions to [the Pushy mailing list](https://groups.google.com/d/forum/pushy-apns) because:

1. The mailing list has a wider audience, and you're more likely to find somebody who has experience with your particular question on the mailing list.
2. Posting your question to the mailing list can help other people who have the same question.
3. Because there isn't a bug to fix or a feature to add, we can't reasonably solve your problem by making any kind of engineering change.

I emphasize that this is a discussion we'd be happy to have, but let's move it to a different venue. In the meantime, it's probably worth noting that we currently have no plans to add GCM/FCM support to Pushy; if Turo winds up cooking up something for GCM/FCM, we'd almost certainly do it in a separate project.

Cheers!
