### ISSUE TITLE
Manually trigger the FailedConnectionListener

### ISSUE THREAD

**Issue by SigalGivati** [relayrides/pushy#419]
I registered FailedConnectionListener class to handle failed connection exception.. I need to test that the listener is triggered by the cause of SSLHandshakeException. 
Is there a way to manually generate that exception with that cause?

**Comment by jchambers** [comment]
Hello!

This sounds more like a request for general support than it does like a bug report or a feature request. We generally ask people to move these kinds of questions to [the Pushy mailing list](https://groups.google.com/d/forum/pushy-apns) because:

1. The mailing list has a wider audience, and you're more likely to find somebody who has experience with your particular circumstances on the mailing list.
2. Posting your question to the mailing list can help other people who are having the same problem.
3. Because there isn't a bug to fix or a feature to add, we can't reasonably solve your problem by making any kind of engineering change.

I emphasize that we'd be happy to help, but let's move this conversation to a different venue.

That said, it sounds like you're using a very old version of Pushy. My strong recommendation is to update to one of the more recent HTTP/2-based versions, which don't have `FailedConnectionListeners` at all. If you go so far as to adopt token-based authentication, the probability if running into an `SSLHandshakeException` in the wild becomes very low (as opposed to a routine occurrence when client certificates expire).

If you really want to simulate this failure, though, I'd recommend trying to connect to something with a known-bad certificate.

Since this isn't a bug report or feature request (and there's nothing we can do in code to resolve this issue), I'm going to close this issue. If you need further assistance, we'd be happy to help you on the mailing list.
