### ISSUE TITLE
Using pushy in Linux

### ISSUE THREAD

**Issue by kish-pisces** [relayrides/pushy#420]
I am using 
Java 7
pushy:0.9.1
netty-tcnative-boringssl-static: 1.1.33.Fork24

It working all fine in windows with tomcat. I am able to send push notification successfully.

Now when I deploy the same in Websphere (in Linux box), I get below error

java.lang.UnsatisfiedLinkError : netty-tcnative-linux-x86_64-fedora (not found in java.library.path)

Please help.

**Comment by jchambers** [comment]
Hello!

This sounds more like a request for general support than it does like a bug report or a feature request. We generally ask people to move these kinds of questions to [the Pushy mailing list](https://groups.google.com/d/forum/pushy-apns) because:

1. The mailing list has a wider audience, and you're more likely to find somebody who has experience with your particular circumstances on the mailing list.
2. Posting your question to the mailing list can help other people who are having the same problem.
3. Because there isn't a bug to fix or a feature to add, we can't reasonably solve your problem by making any kind of engineering change.

I emphasize that we'd be happy to help, but let's move this conversation to a different venue.
