### ISSUE TITLE
Token size error

### ISSUE THREAD

**Issue by EagleGlance** [relayrides/pushy#424]
Hello dear colleagues!
I use you library for sending Apple push notifications version 0.4.3 and I faced with trouble 

```
09:45:07.113 [nioEventLoopGroup-2-1] DEBUG com.relayrides.pushy.apns.ApnsConnection - APNs gateway rejected notification with sequence number 1 from JoinyPushManager-connection-0 (INVALID_TOKEN_SIZE)
```

I sure that the problem is not associated with a certificates and a choice between dev or prod environments.
Can you give the answer about this situation and what i should fixed in code? I used valid token with 64 symbols that converts in byte array with size 32.

Best regards, Viachaslau Kalevich
Software Engineer

[IssueTokenSize.txt](https://github.com/relayrides/pushy/files/769448/IssueTokenSize.txt)

**Comment by jchambers** [comment]
Hello!

This sounds more like a request for general support than it does like a bug report or a feature request. We generally ask people to move these kinds of questions to [the Pushy mailing list](https://groups.google.com/d/forum/pushy-apns) because:

1. The mailing list has a wider audience, and you're more likely to find somebody who has experience with your particular circumstances on the mailing list.
2. Posting your question to the mailing list can help other people who are having the same problem.
3. Because there isn't a bug to fix or a feature to add, we can't reasonably solve your problem by making any kind of engineering change.

I emphasize that we'd be happy to help, but let's move this conversation to a different venue.
