### ISSUE TITLE
question. Programmatically unsubscribe

### ISSUE THREAD

**Issue by publicocean0** [relayrides/pushy#430]
is there a way for remove a subscription from my server?

**Comment by jchambers** [comment]
Hello!

This sounds more like a request for general support than it does like a bug report or a feature request. We generally ask people to move these kinds of questions to [the Pushy mailing list](https://groups.google.com/d/forum/pushy-apns) because:

1. The mailing list has a wider audience, and you're more likely to find somebody who has experience with your particular circumstances on the mailing list.
2. Posting your question to the mailing list can help other people who are having the same problem.
3. Because there isn't a bug to fix or a feature to add, we can't reasonably solve your problem by making any kind of engineering change.

I emphasize that we'd be happy to help, but let's move this conversation to a different venue.

That said, I'm a little unclear on what you're asking; when you post to the mailing list, can you please rephrase or provide some additional detail? Thanks!
