### ISSUE TITLE
jdk1.8 test error

### ISSUE THREAD

**Issue by xweichen** [relayrides/pushy#436]
i created a maven project and used oracle jdk1.8 ,when i test push code i get a error

```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" java.lang.NoClassDefFoundError: io/netty/util/internal/logging/InternalLoggerFactory
	at io.netty.handler.ssl.OpenSsl.<clinit>(OpenSsl.java:52)
	at com.relayrides.pushy.apns.ApnsClientBuilder.build(ApnsClientBuilder.java:393)
...
```

and the pom.xml file 

```xml
<dependencies>
	<dependency>
		<groupId>com.relayrides</groupId>
		<artifactId>pushy</artifactId>
		<version>0.9.2</version>
	</dependency>
	
	<dependency>
		<groupId>org.eclipse.jetty.alpn</groupId>
		<artifactId>alpn-api</artifactId>
		<version>1.1.3.v20160715</version>
	</dependency>
</dependencies>
```

I don't know what is missing?

**Comment by jchambers** [comment]
Hello!

I strongly suspect this may be specific to your development environment (because if it weren't, eeeeeeverybody would be complaining about it). As a result, this sounds more like a request for general support than it does like a bug report or a feature request. We generally ask people to move these kinds of questions to [the Pushy mailing list](https://groups.google.com/d/forum/pushy-apns) because:

1. The mailing list has a wider audience, and you're more likely to find somebody who has experience with your particular circumstances on the mailing list.
2. Posting your question to the mailing list can help other people who are having the same problem.
3. Because there (probably) isn't a bug to fix or a feature to add, we can't reasonably solve your problem by making any kind of engineering change.

I emphasize that we'd be happy to help, but let's move this conversation to a different venue.

In the meantime, my best guess is that Maven has just cached something weird on your end; have you tried clearing your Maven cache and rebuilding your project?

Cheers!
