### ISSUE TITLE
Enable pushy's log

### ISSUE THREAD

**Issue by binauyang** [relayrides/pushy#470]
Hi @jchambers ,
Could you tell me how to enable pushy's log, so that I can get more information when some exceptions occur? Thank you.

**Comment by jchambers** [comment]
Hello!

This sounds more like a request for general support than it does like a bug report or a feature request. We generally ask people to move these kinds of questions to [the Pushy mailing list](https://groups.google.com/d/forum/pushy-apns) because:

1. The mailing list has a wider audience, and you're more likely to find somebody who has experience with your particular circumstances on the mailing list.
2. Posting your question to the mailing list can help other people who are having the same problem.
3. Because there isn't a bug to fix or a feature to add, we can't reasonably solve your problem by making any kind of engineering change.

I emphasize that we'd be happy to help, but let's move this conversation to a different venue.

In the meantime (and at the risk of asking the obvious), have you tried following the [instructions for setting up slf4j bindings](https://github.com/relayrides/pushy#logging) in the README?

**Comment by binauyang** [comment]
OK, and the problem is solved! Thanks!
