### ISSUE TITLE
how to set the number of parallel connections

### ISSUE THREAD

**Issue by qiankunli** [relayrides/pushy#473]
in the introduction to pushy, "it's easy and efficient to maintain multiple parallel connections to the APNs gateway to send large numbers of notifications to many different applications ("topics")."

so, how to set the number of parallel connections?

**Comment by jchambers** [comment]
Right now, you need to create a separate `ApnsClient` for each app. You can share an `EventLoopGroup` between clients to keep the thread count under control; please see [`ApnsClientBuilder#setEventLoopGroup(EventLoopGroup)`](http://relayrides.github.io/pushy/apidocs/0.10/com/turo/pushy/apns/ApnsClientBuilder.html#setEventLoopGroup-io.netty.channel.EventLoopGroup-) for more information.

We intend to add support for multiple apps with a single client eventually, though recently hit a major upstream roadblock. It turns out that, even with token-based authentication, the APNs server will reject tokens from teams beyond the first on a single connection. Our original token-based authentication design allowed clients to have keys for multiple teams, but we had to roll that back in [v0.10](https://github.com/relayrides/pushy/releases/tag/pushy-0.10) when we learned about the upstream limitation.
