### ISSUE TITLE
only show notification  title，can not show notification message

### ISSUE THREAD

**Issue by qiankunli** [relayrides/pushy#482]
![image](https://user-images.githubusercontent.com/8024725/27331455-18f49f42-55f0-11e7-875c-af18ff547afd.png)

when click the notification, it can jump the page of "喜马拉雅FM" app with extra data correctly

environment:
pushy version: 0.10

**Comment by jchambers** [comment]
I think we're going to need some more information to be able to perform any meaningful debugging here. Some questions:

1. What does the payload for this notification look like?
2. What do you think the payload *should* look like?
3. Did this work with an earlier version of Pushy?
4. Which version of iOS is this?
5. Did it work with a previous version of iOS?

To share some early thoughts, APNs itself is generally not concerned with the content of notifications. Interpreting and displaying the content happens entirely (a) in iOS and (b) the receiving application. If we're putting together an incorrectly-formed payload, it's definitely our fault. If we're sending the correct payload and it's being displayed in a weird way, the problem is almost certainly somewhere else.

Thanks!
