### ISSUE TITLE
ping problem

### ISSUE THREAD

**Issue by Tielancy** [relayrides/pushy#493]
some codes in ApnsClient like this:

```java
context.pipeline().addLast(new IdleStateHandler(0, 0, ApnsClient.this.idlePingIntervalMillis, TimeUnit.MILLISECONDS));
```

this config asserts read and write, but when channel has something wrong which results that bytes can only be send to(no exception thrown, actually, this bytes not received by remote endpoint) but no response from remote endpoint. If that, no IdleStateEvent will happen and reconnect does not work.

So, I think that config should be like this:

```java
context.pipeline().addLast(new IdleStateHandler(ApnsClient.this.idlePingIntervalMillis, 0, 0, TimeUnit.MILLISECONDS));
```

**Comment by jchambers** [comment]
I see where you're going with this, but just to confirm (and to explain for those who maybe aren't intimately familiar with the [`IdleStateHandler` constructor arguments](http://netty.io/4.1/api/io/netty/handler/timeout/IdleStateHandler.html#IdleStateHandler-long-long-long-java.util.concurrent.TimeUnit-)), I think you're suggesting that instead of waiting for read AND write to go idle, we ONLY wait for read to go idle before sending a `PING` frame. Is that accurate?

If so, I think that makes sense.

**Comment by Tielancy** [comment]
Yes, just need ONLY wait for read to go idle before sending a PING frame.If wait for write, may result in no Ping frame could be send when network failure but data frame still can be sent.
