### ISSUE TITLE
Delayed Response from Apple's APNS Server using HTTP/2

### ISSUE THREAD

**Issue by atanu-pal** [relayrides/pushy#501]
My project is using Pushy Library to send APNS to iOS devices from last one year, recently we upgraded Pushy to use HTTP/2 mechanism for sending APNS. (our application is in Java 8)

It works as it supposed to in our test environment, but when We installed it on client's machine we are getting following error:

```
io.netty.handler.ssl.ApplicationProtocolNegotiationHandler.handshakeFailure : [id: 0x581db609, L:/IP-Address:58781 - R:api.push.apple.com/17.188.140.153:443] TLS handshake failed: javax.net.ssl.SSLException: handshake timed out
```

I checked for everything available on forums but nothing seems to help.

As a last resort I tried looking into Wireshark to see the difference between my test environment & client environment, what I see is the "Server Hello" message is getting delayed due to which the connection times out.

Snapshot of WireShark Capture:
![wireshark_1280](https://user-images.githubusercontent.com/15432051/28960715-5b492016-791d-11e7-9f06-958226e87b06.png)

You can see the delay in "Server Hello" & what I observed the "Server Hello" always comes after "Close Notify" is sent by a client, exactly after 10 seconds. As per my understanding its done by the client to say we are timing out on the connection.

I tried increasing connection time-out value in Pushy, but it did not work, but that may be a different question, I think.

Can someone tell me what are we doing wrong? Is there some setting we have to do on client's network to enable HTTP/2? Is there something I have to change in Pushy Library?

**Comment by atanu-pal** [comment]
FYI: I have posted same over StackOverflow, Link:
https://stackoverflow.com/questions/45500359/delayed-response-from-apples-apns-server-using-http-2

**Comment by jchambers** [comment]
Hello!

This sounds more like a request for general support than it does like a bug report or a feature request. We generally ask people to move these kinds of questions to [the Pushy mailing list](https://groups.google.com/d/forum/pushy-apns) because:

1. The mailing list has a wider audience, and you're more likely to find somebody who has experience with your particular circumstances on the mailing list.
2. Posting your question to the mailing list can help other people who are having the same problem.
3. Because there isn't (I think!) a bug to fix or a feature to add, we can't reasonably solve your problem by making any kind of engineering change.

To be clear, I acknowledge that whatever is going wrong here is technical in nature, but it seems unlikely to be a bug in Pushy itself (if it were in Pushy, it seems like many more people would be having this problem). I suspect there might be something fishy going on with a firewall or some other piece of network configuration.

I emphasize that we'd be happy to help, but let's move this conversation to a different venue. Thanks!
