### ISSUE TITLE
Use of ReferenceCountedSSLContext

### ISSUE THREAD

**Issue by flozano** [relayrides/pushy#502]
Context: 
With latest pushy 0.10.1, we keep having increased RSS memory usage. However, even in PARANOID mode there are no LEAKs reported by netty's detector. There is no other direct memory use in the system other than pushy... so, if netty's buffers are not to blame, we are strongly suspicious of tcnative. We have a high reconnection rate, many connections with expired certificates and such.

- Do you plan to implement the use of ReferenceCountedSSLContext? 
- Can you suggest way for us to try to identify that the netty-tcnative not releasing memory is what's happening to us?

**Comment by jchambers** [comment]
> Do you plan to implement the use of ReferenceCountedSSLContext?

Yes. This will be easier after we move to a connection-pooled client (see #492) because we need to explicitly release each `SslContext`.

> Can you suggest way for us to try to identify that the netty-tcnative not releasing memory is what's happening to us?

Sadly, I'm really not sure. I know that direct memory is somewhat notorious for being difficult to garbage-collect; that may be what's happening here. Do you ever truly run out? Is it possible that it'll just keep piling up until there's a biiiiig GC pass later?

In any case, yeah—I definitely hope reference-counted SSL will resolve the issue.

**Comment by flozano** [comment]
> Do you ever truly run out? Is it possible that it'll just keep piling up until there's a biiiiig GC pass later?
No, we even get OOM killer to kill the Java process. It's direct memory leak for sure.

**Comment by jchambers** [comment]
Reference-counted SSL providers were restored in #515.
