### ISSUE TITLE
Setting up Pushy to use Jetty ALPN

### ISSUE THREAD

**Issue by meanwhileinhell** [relayrides/pushy#504]
Not sure if this is the right forum to post this, if not, apologies.

When setting up Pushy to use Jetty ALPN Agent as a java agent passed to the JVM (as is the recommended approach), is it only required that you add two additional args, and that no Java code changes are required?:

`-Xbootclasspath/p:<path>/jetty-alpn-agent-2.0.0.jar`
`-javaagent:<path>/jetty-alpn-agent-2.0.0.jar`

with this in my build.gradle file:

`compile group: 'org.mortbay.jetty.alpn', name: 'jetty-alpn-agent', version '2.0.0'`

Is there a FAQ article on how to set this up, as I notice its asked a few times.  Any help would be greatly appreciated!

**Comment by jchambers** [comment]
Hello!

This sounds more like a request for general support than it does like a bug report or a feature request. We generally ask people to move these kinds of questions to [the Pushy mailing list](https://groups.google.com/d/forum/pushy-apns) because:

1. The mailing list has a wider audience, and you're more likely to find somebody who has experience with your particular circumstances on the mailing list.
2. Posting your question to the mailing list can help other people who are having the same problem.
3. Because there isn't a bug to fix or a feature to add, we can't reasonably solve your problem by making any kind of engineering change.

I emphasize that we'd be happy to help, but let's move this conversation to a different venue.

In the meantime, please note that you do *not* need to put `jetty-alpn-agent` on your boot class path (you *would* need to do this if you were adding `alpn-boot` directly); you just need to add `jetty-alpn-agent` as an agent.
