### ISSUE TITLE
ApnsClient Reconnection issue 

### ISSUE THREAD

**Issue by prakashpandey** [relayrides/pushy#512]
**Case 1** : I tried to to establish ApnsClient connection by providing wrong .p12 file (development .p12 file in case of production).
What I found is, Pushy try to reconnect to APNS over and over again. 

**Case 2** : Also as per my knowledge, Push also try to reconnect if there is some problem in network which is a fine behavior. 

What I am trying to achieve is, I want to reconnect only in **case 2** and not in **case 1**.

Is it possible in pushy?

**Comment by ricardopt** [comment]
The thing is how you find out that the .p12 is wrong. You can parse some part of it and try to match _i.e._ the topic but the other information will be truly difficult to fact check.

After googling a bit I found on the documentation this:

403 | There was an error with the certificate or with the provider authentication token
-- | --

Maybe we could add some feature there. I will sleep on it.

**Comment by prakashpandey** [comment]
Yes, we should have this as a feature.

Reconnecting connection for a wrong credentials in production will consume unnecessary resource.

**Comment by jchambers** [comment]
We need to separate a few ideas to get at the core of the problem. First, it's important to note that there are now two ways for clients to authenticate with the APNs server: they may _either_ perform mutual TLS authentication by presenting a client certificate _or_ they may opt out of mutual TLS authentication and provide an authentication token when sending notifications (i.e. _after_ connecting) instead.

One key difference between the two approaches is that mutual TLS authentication is happening at connection time, and thus can interfere with the connection process. Client certificates can expire, and the process of constructing a correctly-formed PKCS#12 file is non-trivial. Unfortunately, there are lots of things that can go wrong—even at the TLS handshake level—and it's extremely difficult for us to conclude with certainty that the thing that went wrong is a permanent failure attributable directly to the provided client credentials. It's really really hard for us to tell the difference, for example, between a connection failure caused by a bad certificate and a connection failure caused by the APNs server's certificate missing from the JVM's trust store.

This means that we have a situation where we can't be certain that stopping all connection attempts is the right thing to do. We _do_ provide a [metrics system](http://relayrides.github.io/pushy/apidocs/0.10/com/turo/pushy/apns/ApnsClientMetricsListener.html) that callers can use to watch for high rates of reconnection and make that decision on their own, though.

It's important to note that if you're using token-based authentication, bogus client credentials can still be a problem, but will not interfere with establishing a connection to the server.

Because Apple now provides an authentication scheme that does not suffer from this problem, because we provide tools (in the form of metrics listeners) for callers to deal with the situation themselves, and because a "fix" in Pushy would risk shutting down clients inappropriately, we will not implement the feature you're requesting.

I'd strongly encourage you to try token-based authentication as a simple way to mitigate this problem. I'd also encourage you to take a look at the reconnection improvements in #492, which I think will go a long way to addressing some adjacent concerns.

In the meantime, thank you for the suggestion! Please don't hesitate to reach out if you have other feature requests or questions.

Cheers!

**Comment by ricardopt** [comment]
We have to analyze the documentation regarding MDM. I know there are some differences, I don't know by heart all the issues involved but it can implicate that we still had to maintain the TLS certificate authentication.

In order to put the MDM working, you need a different certificate that the one you need to send a normal push notification.
