### ISSUE TITLE
MvnCentral repository id

### ISSUE THREAD

**Issue by ricardopt** [relayrides/pushy#513]
Hello,

I want to add a configuration to the pom's. But I need the id that the repository has on the maven central.
Can someone provide me that information?

Thanks

**Comment by prakashpandey** [comment]
<dependency>
    <groupId>com.turo</groupId>
    <artifactId>pushy</artifactId>
    <version>0.10.2</version>
</dependency>

**Comment by jchambers** [comment]
Hello!

This sounds more like a request for general support than it does like a bug report or a feature request. We generally ask people to move these kinds of questions to [the Pushy mailing list](https://groups.google.com/d/forum/pushy-apns) because:

1. The mailing list has a wider audience, and you're more likely to find somebody who has experience with your particular circumstances on the mailing list.
2. Posting your question to the mailing list can help other people who are having the same problem.
3. Because there isn't a bug to fix or a feature to add, we can't reasonably solve your problem by making any kind of engineering change.

I emphasize that we'd be happy to help, but let's move this conversation to a different venue.
