### ISSUE TITLE
Repository ID on mvn central

### ISSUE THREAD

**Issue by ricardopt** [relayrides/pushy#514]
Hello,

Yesterday I opened an issue asking for the mvn central id. Somehow the post was deleted. I want to add functionality to the POM that needs the repository id.

I don't understand what is the problem with my post and why someone is deleting it.

--
Regards,

**Comment by jchambers** [comment]
For posterity, the other issue in question was #513. It was closed—not deleted—with a request to move the discussion to the mailing list because it is strictly a request for information/support and can't be resolved with a change to Pushy itself.

@ricardopt because you've closed this issue, I'm assuming you came to the same conclusion. I look forward to assisting you in a more appropriate venue.
