### ISSUE TITLE
Sending JSONObject as value in ApnsPayloadBuilder.addCustomProperty

### ISSUE THREAD

**Issue by prakashpandey** [relayrides/pushy#545]
I am trying to send **JSONObject** as **value** for a property _prop2_ by using _addCustomProperty_ of _ApnsPayloadBuilder_.

```
final ApnsPayloadBuilder payloadBuilder = new ApnsPayloadBuilder();
payloadBuilder.addCustomProperty(key, value);
```

If my value is JSONObject, I am receiving the following payload on my client IOS app: 

```
{
    "prop1" = 1;
    "prop2" =     {
        map =         {
            content = "https://images.pexels.com/photos/67636/rose-blue-flower-rose-blooms-67636.jpeg";
            key = value;
            type = image;
        };
    };
    aps =     {
        alert =         {
            body = "single user message with attachment";
        };
        "mutable-content" = 1;
        sound = default;
    };
}
```

Value of `prop2` is **expected** JSONObject but what I am receiving on the client side is:  

```
 map =         {
            content = "https://images.pexels.com/photos/67636/rose-blue-flower-rose-blooms-67636.jpeg";
            key = value;
            type = image;
        };
```

**Comment by jchambers** [comment]
Where does `JSONObject` come from? Is it a class that you've created, or does it come from a third-party library?

**Comment by prakashpandey** [comment]
Third party (org.json)

**Comment by jchambers** [comment]
Hm. I'm not sure what should happen here, but I'll definitely admit that [the docs for `ApnsPayloadBuilder#addCustomProperty(String, Object)`](http://relayrides.github.io/pushy/apidocs/0.11/com/turo/pushy/apns/util/ApnsPayloadBuilder.html#addCustomProperty-java.lang.String-java.lang.Object-) don't adequately explain how the `Object` will get turned into JSON. What _is_ happening is that we're always using `Object#toString()` if the object isn't a type that has a direct equivalent in JSON (a string, number, list, or map).

There are two ways we can go:

1. Use introspection to read properties from Java objects and convert Java objects into JSON maps. Lots of JSON tools do this, but I'm not sure if it's what we want (or what callers would expect) in this case.
2. Continue the direct-mapping-to-JSON-type-or-else-string approach. In this case, callers like @prakashpandey would need to construct a `Map` that represents their JSON object. We could add more type-specific methods to clarify the behavior in this case (i.e. get rid of `addCustomProperty(String, Object)` and add `addCustomProperty(String, Map)`, `addCustomProperty(String, Number)`, etc.). This may be less convenient, but would also be clearer.

We can't really special-case things like `org.json.JSONObject` because we'd then need to add a special case for every JSON library out there, and that's just not practical.

What do you all think?

And @prakashpandey, as a quick workaround, it's worth noting that you don't _need_ to use `ApnsPayloadBuilder`. If you just want to go straight to building a full payload with `org.json`, that's totally fine. Pushy just wants a string for the payload, and there's no magic about the strings that come from `ApnsPayloadBuilder`.

**Comment by jchambers** [comment]
Waaaaaaait a second. I didn't think this all the way though. I'm not actually sure what gson is doing under the hood, and it may indeed be using introspection to convert POJOs to JSON. I'll verify this shortly. Either way, though, `org.json.JSONObject` is neither a POJO nor a `Map`, AND `JSONObject#toString()` doesn't produce a JSON representation of that object. As a result, there really isn't any way for us to gracefully handle `org.json.JSONObjects` as custom properties. @prakashpandey you'll need to either convert your custom object to a `Map` or (depending on how this investigation goes) a POJO.

…also, as a brief moment of rhetorical arm-flailing, why in the world would somebody decide that `JSONObject#toString()` should produce something other than the JSON representation of that object?

**Comment by jchambers** [comment]
Wrong again! `JSONObject#toString()` _does_ produce legal JSON.

@prakashpandey I'm looking more closely at your initial example, and now I'm very confused and not sure I understand the problem. The text you're showing is _not_ legal JSON in either example. Also, I'm not seeing what's different about the value for `prop2` between the two examples.

I _think_ what you're showing us is the result of `NSLog(someNSDictionaryThatComesFromThePayload)` on the receiving device; is that correct? If so, can you please restate/rephrase what you think is incorrect?

**Comment by panchenko** [comment]
Gson does serialization using field access, but it's aware of standard types, like Map/List.
So I think JSONObject contains the `private Map map` field - and we see in the example.

**Comment by jchambers** [comment]
> So I think JSONObject contains the private Map map field - and we see it in the example.

Agreed. Pardon all of the confusion and tail-chasing on this point; I read far too quickly at the beginning and jumped to a bunch of inaccurate conclusions.

@prakashpandey is the complaint that you're seeing this…

```
"prop2" =     {
    map =         {
        content = "https://images.pexels.com/photos/67636/rose-blue-flower-rose-blooms-67636.jpeg";
        key = value;
        type = image;
    };
};
```

…but want this?

```
"prop2" =     {
    content = "https://images.pexels.com/photos/67636/rose-blue-flower-rose-blooms-67636.jpeg";
    key = value;
    type = image;
};
```

**Comment by prakashpandey** [comment]
Yes exactly.

This is what I want:

"prop2" =     {
    content = "https://images.pexels.com/photos/67636/rose-blue-flower-rose-blooms-67636.jpeg";
    key = value;
    type = image;
};

**Comment by jchambers** [comment]
Okay. Thanks for the clarification.

As hinted earlier, we mostly can't/won't change the behavior for `JSONObject` in particular. What we _can_ do is update the documentation to be clearer about how objects get turned into JSON.

In your particular case, you can achieve the result you want by:

1. Creating a `Map` instead of a `JSONObject` and passing that as the value for your custom property.
2. Creating a a plain Java object with the properties you want and passing that as the value for the custom property; GSON will extract the properties from your object and serialize them as JSON.

Here's an example of the latter approach:

```java
public class PayloadTest {

    private static class ExamplePojo {
        private final int aThing = 12;
        private final List<String> someStrings = Arrays.asList("One", "Two", "Three");

        public int getaThing() {
            return aThing;
        }

        public List<String> getSomeStrings() {
            return someStrings;
        }
    }

    public static void main(final String... args) {
        System.out.println(new ApnsPayloadBuilder()
                .addCustomProperty("customProperty", new ExamplePojo())
                .buildWithDefaultMaximumLength());
    }
}
```

The above will give you a payload that looks like this:

```json
{"aps":{},"customProperty":{"aThing":12,"someStrings":["One","Two","Three"]}}
```

**Comment by jchambers** [comment]
Docs have been updated in #546.

**Comment by prakashpandey** [comment]
Ok thanks for quick response. Currently how I solved my problem is by converting every custom property to .toString().

Also I will try it out with custom Java class.
