### ISSUE TITLE
Un-registered user response from pushy

### ISSUE THREAD

**Issue by prakashpandey** [relayrides/pushy#548]
I have an IOS app registered with my `.p12` file. Suppose a user of my application uninstalls the app. 

My question is can I know un-registered user using pushy by sending push-notification or what response from `pushy` will I receive when I send push to the above un-installed user

**Comment by jchambers** [comment]
Hello!

This sounds more like a request for general support than it does like a bug report or a feature request. We generally ask people to move these kinds of questions to [the Pushy mailing list](https://groups.google.com/d/forum/pushy-apns) because:

1. The mailing list has a wider audience, and you're more likely to find somebody who has experience with your particular circumstances on the mailing list.
2. Posting your question to the mailing list can help other people who are having the same problem.
3. Because there isn't a bug to fix or a feature to add, we can't reasonably solve your problem by making any kind of engineering change.

I emphasize that we'd be happy to help, but let's move this conversation to a different venue.

In the meantime, please see the [APNs documentation](https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/CommunicatingwithAPNs.html#//apple_ref/doc/uid/TP40008194-CH11-SW1). You'll eventually receive an `Unregistered` response, but there are no guarantees as to when the APNs server will start sending `Unregistered` instead of accepting the notification and failing to deliver it.
