### ISSUE TITLE
Unable to open input stream for resource netty-common-4.1.16.Final.jar

### ISSUE THREAD

**Issue by iosnewbie2016** [relayrides/pushy#549]
Hi - When am trying to use the pushy jar with netty jars on IBM WAS, it gives me an error on my server startup. I googled but could not find any solution. Can you pls help me with it?

Error:
com.ibm.ws.ecs.internal.scan.context.impl.ScannerContextImpl scanJAR unable to open input stream for resource io/netty/util/internal/shaded/org/jctools/queues/package-info.class in archive WEB-INF/lib/netty-common-4.1.16.Final.jar

Pls let me know if you need more details.

**Comment by jchambers** [comment]
Hello!

This sounds more like a request for general support than it does like a bug report or a feature request. We generally ask people to move these kinds of questions to [the Pushy mailing list](https://groups.google.com/d/forum/pushy-apns) because:

1. The mailing list has a wider audience, and you're more likely to find somebody who has experience with your particular circumstances on the mailing list.
2. Posting your question to the mailing list can help other people who are having the same problem.
3. Because there isn't a bug to fix or a feature to add, we can't reasonably solve your problem by making any kind of engineering change.

I emphasize that we'd be happy to help, but let's move this conversation to a different venue.
