### ISSUE TITLE
Stream closed before a reply was received

### ISSUE THREAD

**Issue by yuweibo** [relayrides/pushy#552]
```
java.io.IOException: Stream closed before a reply was received
java.util.concurrent.ExecutionException: java.io.IOException: Stream closed before a reply was received
	at io.netty.util.concurrent.AbstractFuture.get(AbstractFuture.java:41)
```

**Comment by jchambers** [comment]
Based on the (extremely limited) information you've shared, there's no reason to believe this is a bug. It sounds like your connection to the server closed unexpectedly, and so we never got a reply from the server. Reporting this exception as a write failure is exactly what Pushy is supposed to do.

I'm going to close this issue because there is no indication that anything is actually wrong. If you'd like us to take another look, you'll need to provide _much_ more information. For example, what were you trying to do when this happened? Why do you think it's incorrect? What do you think should happen instead?

**Comment by yuweibo** [comment]
apns1 still on my system,so some tokens not match apns2 make this exception,thanks.

**Comment by kulswaroop** [comment]
@yuweibo could you please explain a bit more about your comment. I am also facing same issue and not really sure how to check if apns1 still exists on my system !

**Comment by yuweibo** [comment]
@kulswaroop hi，i just want more length of payload，so i fixed apns1 to 2048，you have to make sure token version if you want apns2.:stuck_out_tongue_winking_eye:
