### ISSUE TITLE
getting io.netty.channel.abstractchannel$annotatedconnectexception: connection timed out: no further information while sending notification

### ISSUE THREAD

**Issue by manisha0610** [relayrides/pushy#569]
Hi,
currently we are using v0.4.3 in my application and now upgrading it to latest version 0.11.3
made relevant code changes, not sure right or not, but getting connection issue while connecting using Certificates

Any help will be appreciated.
Thanks in advance

**Comment by jchambers** [comment]
Hello!

This sounds more like a request for general support than it does like a bug report or a feature request. We generally ask people to move these kinds of questions to [the Pushy mailing list](https://groups.google.com/d/forum/pushy-apns) because:

1. The mailing list has a wider audience, and you're more likely to find somebody who has experience with your particular circumstances on the mailing list.
2. Posting your question to the mailing list can help other people who are having the same problem.
3. Because there isn't a bug to fix or a feature to add, we can't reasonably solve your problem by making any kind of engineering change.

I emphasize that we'd be happy to help, but let's move this conversation to a different venue. In the meantime, please note that the host and port for the APNs server are different for the new HTTP/2-based APNs API. Do you need to change your firewall settings? Are you using a proxy?
