### ISSUE TITLE
Handling of enqueued notification upon apns client closing

### ISSUE THREAD

**Issue by DamienDub** [relayrides/pushy#574]
Hi all,

In my use case I need to close the apns client right after sending a batch of notifications. So after sending all notifications with the corresponding listeners I call
```
final Future<Void> closeFuture = apnsClient.close();
closeFuture.await();
```
The problem is that all notifications that have been enqueued but not sent get lost.

The README suggests to 

> make sure that all sent notifications have been acknowledged by the server before shutting down

Is there a proper way of doing so?

**Comment by jchambers** [comment]
Hello!

This sounds more like a request for general support than it does like a bug report or a feature request. We generally ask people to move these kinds of questions to [the Pushy mailing list](https://groups.google.com/d/forum/pushy-apns) because:

1. The mailing list has a wider audience, and you're more likely to find somebody who has experience with your particular circumstances on the mailing list.
2. Posting your question to the mailing list can help other people who are having the same problem.
3. Because there isn't a bug to fix or a feature to add, we can't reasonably solve your problem by making any kind of engineering change.

I emphasize that we'd be happy to help, but let's move this conversation to a different venue.

In the meantime, the most common approach is to hold on to the `Futures` returned by `sendNotification` and either `.await()` all of them or add listeners that use something like a [`CountDownLatch`](https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/CountDownLatch.html) to keep track of how many `Futures` have been resolved.
