### ISSUE TITLE
Pushy will buffer notifications automatically

### ISSUE THREAD

**Issue by gcr1992** [relayrides/pushy#586]
The APNs server allows for (at the time of this writing) 1,500 notifications in flight at any time. If we hit that limit, **Pushy will buffer notifications automatically** behind the scenes and send them to the server as in-flight notifications are resolved.

Can anyone tell me how this code is implemented？
Thanks.

**Comment by jchambers** [comment]
Hello!

This sounds more like a request for general support than it does like a bug report or a feature request. We generally ask people to move these kinds of questions to [the Pushy mailing list](https://groups.google.com/d/forum/pushy-apns) because:

1. The mailing list has a wider audience, and you're more likely to find somebody who has experience with your particular circumstances on the mailing list.
2. Posting your question to the mailing list can help other people who are having the same problem.
3. Because there isn't a bug to fix or a feature to add, we can't reasonably solve your problem by making any kind of engineering change.

I emphasize that we'd be happy to help, but let's move this conversation to a different venue. In the meantime, the short answer is "[Netty](http://netty.io/) just takes care of it."

**Comment by gcr1992** [comment]
Ok,thanks
