### ISSUE TITLE
Sending single message for multiple devices

### ISSUE THREAD

**Issue by AnanlaTech** [relayrides/pushy#592]
SimplePushNotification class accept only one tokens and for each token we are generating the simple push notification class instance instead is there any simple approach to send same message for multiple devices

**Comment by jchambers** [comment]
> is there any simple approach to send same message for multiple devices

Well, I think you mean "is there a method in Pushy to do this," to which the answer is "no." To literally answer your question, though, there is indeed a simple way to send the same message to multiple devices: just use a `for` loop.

We have declined to implement a "multi-send" feature in the past for two main reasons:

1. There's no protocol-level notion of sending the same notification to multiple devices, and so our internal implementation of such a method would just be a `for` loop anyhow.
2. It's unclear what a "multi-send" method should return. Should it be a single `Future`? If so, what happens if some notifications are accepted and some are rejected? There are a range of reasonable answers to these questions, but none will be right for everybody.

Because the need is easily met outside of Pushy and because an attempt to build a multi-send feature into Pushy would have a complexity cost way out of proportion to the benefits, we will not implement this feature in the foreseeable future.
