### ISSUE TITLE
APNSClient Reconnection Issue

### ISSUE THREAD

**Issue by rakeshselvam** [relayrides/pushy#600]
Hi @jchambers 

We are facing problem with auto reconnect mechanism when the connection is dropped because of network outage. Our application CPU usage increased very high when Pushy trying to reconnects and finally application got crashed around 45 minutes to one hour of retrying connection.

We are using "Pushy v0.9.3" and in application running in JDK 8.

Can someone help me how to resolve this issue.

Regards
Rakesh

**Comment by jchambers** [comment]
Pushy 0.9.3 is, at this point, quite old. Please use the latest version of Pushy (currently 0.12.1), which includes improvements to connection handling (including reconnection).

**Comment by rakeshselvam** [comment]
It's running in production environment, need some quick fix to resolve it. Anyhow we will upgrade to latest version.  Is there any way to stop / disable auto reconnect mechanism.

Thanks for your reply.

**Comment by rakeshselvam** [comment]
@jchambers, Can you provide some work around?

**Comment by jchambers** [comment]
> Can you provide some work around?

No. I don't know enough about your specific circumstances to offer meaningful advice. Please see the [v0.9 `ApnsClient` documentation](http://relayrides.github.io/pushy/apidocs/0.9/com/relayrides/pushy/apns/ApnsClient.html), which explains the old connection mechanics. You'll have to decide what makes the most sense for your particular situation based on the tools available.

Though, again, if you're already considering making changes to your code, I strongly suspect that the most effective path to resolving your problem is just to upgrade to the latest version without trying to hack in a quick fix.

**Comment by rakeshselvam** [comment]
Hi @jchambers 

We are making changes to upgrade Pushy. I have few questions, please clarify:

1. How to enable logs in Pushy? I added "slf4j-api-1.7.25.jar" and "slf4j-log4j12-1.7.25.jar" in application classpath.
2. Previously we used APNSClient.isConnected() method to check connection status, in latest version I don't see such a method in APNSClient class, can you tell what alternative way to know connection status?
3. Is there any listener available to notify improper disconnection?

**Comment by jchambers** [comment]
I think we're veering off course a little. This started as a bug report about CPU load when reconnecting, but is turning into an ongoing thread for technical support. I emphasize that _we're happy to provide support,_ but this is probably the wrong venue. Would you please post these questions to [the mailing list](https://groups.google.com/d/forum/pushy-apns) instead? We generally ask people to move these kinds of questions to the mailing list because:

1. The mailing list has a wider audience, and you're more likely to find somebody who has experience with your particular circumstances on the mailing list.
2. Posting your question to the mailing list can help other people who are having the same problem later, whereas future readers wouldn't know to look in this specific issue for the answers to these questions.
3. Because there isn't a bug to fix or a feature to add, we can't reasonably solve your problem by making any kind of engineering change.

Again, I emphasize that we'd be happy to help, but let's move this conversation to a different venue.
