### ISSUE TITLE
Add apns-collapse-id header in notification 

### ISSUE THREAD

**Issue by NeerajThapliyal** [relayrides/pushy#606]
Hi,
please provide me how to add "apns-collapse-id" in header of request. so that i can replace notification content.

**Comment by jchambers** [comment]
Hello!

This sounds more like a request for general support than it does like a bug report or a feature request. We generally ask people to move these kinds of questions to [the Pushy mailing list](https://groups.google.com/d/forum/pushy-apns) because:

1. The mailing list has a wider audience, and you're more likely to find somebody who has experience with your particular circumstances on the mailing list.
2. Posting your question to the mailing list can help other people who are having the same problem.
3. Because there isn't a bug to fix or a feature to add, we can't reasonably solve your problem by making any kind of engineering change.

I emphasize that we'd be happy to help, but let's move this conversation to a different venue.

In the meantime, I'll point out that support for the collapse-id header is already [in the `ApnsPushNotification` interface](http://relayrides.github.io/pushy/apidocs/0.13/com/turo/pushy/apns/ApnsPushNotification.html#getCollapseId--), and [`SimpleApnsPushNotification` provides a concrete implementation](http://relayrides.github.io/pushy/apidocs/0.13/com/turo/pushy/apns/util/SimpleApnsPushNotification.html#SimpleApnsPushNotification-java.lang.String-java.lang.String-java.lang.String-java.util.Date-com.turo.pushy.apns.DeliveryPriority-java.lang.String-).

**Comment by NeerajThapliyal** [comment]
thanks sir for support.
you save my day.
