### ISSUE TITLE
Native SSL provider not available; will use JDK SSL provider

### ISSUE THREAD

**Issue by hkstar35** [relayrides/pushy#612]
Native SSL provider not available; will use JDK SSL provider

**Comment by jchambers** [comment]
Hello. The message you've pasted here is an informational message from Pushy that indicates which SSL provider it will use. Pushy will work just fine with the JDK SSL provider. This is explained in some detail in the ["Getting Pushy" section of the README](https://github.com/relayrides/pushy#getting-pushy).

This sounds like completely expected behavior with the latest version of Pushy. If you believe that something is not working as expected, please provide additional details. We'd be most interested in:

1. What version of Pushy are you using?
2. What operating system are you using?
3. What were you expecting to happen instead?

I'm going to close this issue for now, but will happily reopen it if you still believe there's a problem and can provide more information.

**Comment by hkstar35** [comment]
Hello, thank you for your reply
use system redhat
Ibm ppc_linux_64
<dependency>
            <groupId>com.turo</groupId>
            <artifactId>pushy</artifactId>
            <version>0.11.3</version>
        </dependency>

**Comment by hkstar35** [comment]
Hello, does the ibm-java-ppc64-sdk-8.0-5.11 version support SSL?

**Comment by jchambers** [comment]
@hkstar35 As far as I know, there is no native pre-built native SSL provider for the PPC architecture. Please use the latest version of Pushy (v0.13.2), which does not require a native SSL provider at all.

**Comment by hkstar35** [comment]
Thank you very much for your reply, thank you
