### ISSUE TITLE
Response Exception : java.lang.IllegalStateException: Channel closed before HTTP/2 preface completed

### ISSUE THREAD

**Issue by nagendra8808** [relayrides/pushy#613]
Dear All,

I am getting the following exception upon triggering sendNotification() method.

my deployment details are as follows

**Container :**

     Jboss 4.3.2 application server

**Operating system :** 

    Red Hat Enterprise Linux Server release 6.4 (Santiago) 
    Release: 6.4 
    LSB Version: :base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch:graphics-4.0-amd64:graphics-4.0-noarch:printing-4.0-amd64:printing-4.0-noarch

**Java version :**

      java version "1.7.0_101"
     Java(TM) SE Runtime Environment (build 1.7.0_101-b14)
     Java HotSpot(TM) 64-Bit Server VM (build 24.101-b14, mixed mode) 
     oracle 

**Artifacts in jboss lib :**

     netty-all-4.1.24.Final.jar
     netty-tcnative-2.0.8.Final.jar
     netty-tcnative-2.0.8.Final-linux-x86_64.jar
     pushy-0.13.2.jar 
     fast-uuid-0.1.jar

Request yours kind help

**Comment by jchambers** [comment]
This appears to be a general support request rather than a bug report, and so I think the mailing list is the right place to have this conversation. That said, I see you've [already posted on the mailing list](https://groups.google.com/d/msg/pushy-apns/aX_oIS0O_kA/6LcUotqBAwAJ), so I'm going to close this issue in the interest of keeping the conversation in a single place.
