### ISSUE TITLE
PushNotification and get the apn server response DeviceTokenNotForTopic

### ISSUE THREAD

**Issue by xiongchunyan** [relayrides/pushy#614]
I have issues about push notification to apn server.And I think it's odd.
This is my code:
`final ApnsClient apnsClient = new ApnsClientBuilder()
				.setApnsServer(ApnsClientBuilder.PRODUCTION_APNS_HOST)
				.setClientCredentials(new File(certPath), key)
				.build();
			
			ApnsPayloadBuilder payloadBuilder = new ApnsPayloadBuilder();
	        String payload = payloadBuilder.buildWithDefaultMaximumLength();
	        
	        String sanitizeToken = TokenUtil.sanitizeTokenString(token);
	        SimpleApnsPushNotification pushNotification = 
	        		new SimpleApnsPushNotification(sanitizeToken, passTypeId, payload);
			
	        final Future<PushNotificationResponse<SimpleApnsPushNotification>> sendNotificationFuture = 
	        		apnsClient.sendNotification(pushNotification);
	        PushNotificationResponse<SimpleApnsPushNotification> pushNotificationResponse = 
	        		sendNotificationFuture.get();
	        
	        if (pushNotificationResponse.isAccepted()) {
	            System.out.println("Push notification accepted by APNs gateway.");
	            System.out.println(pushNotificationResponse.getApnsId());
	        } else {
	            System.out.println("Notification rejected by the APNs gateway: " +
	                    pushNotificationResponse.getRejectionReason());

	            if (pushNotificationResponse.getTokenInvalidationTimestamp() != null) {
	                System.out.println("\t…and the token is invalid as of " +
	                    pushNotificationResponse.getTokenInvalidationTimestamp());
	            }
	        }
	     
	        Future<Void> disconnectFuture = apnsClient.close();
	        disconnectFuture.await();`
when I run in java main method.The notification can accept by apn.But when I deploy the same code to tomcat,and call the interface,will rejecte by apn server and the reason is DeviceTokenNotForTopic.

The Envirment is Java1.8&Tomcat7.Anyone can help me.Thanks very much in advance.

**Comment by jchambers** [comment]
Hello!

This sounds more like a request for general support than it does like a bug report or a feature request. We generally ask people to move these kinds of questions to [the Pushy mailing list](https://groups.google.com/d/forum/pushy-apns) because:

1. The mailing list has a wider audience, and you're more likely to find somebody who has experience with your particular circumstances on the mailing list.
2. Posting your question to the mailing list can help other people who are having the same problem.
3. Because there isn't a bug to fix or a feature to add, we can't reasonably solve your problem by making any kind of engineering change.

I emphasize that we'd be happy to help, but let's move this conversation to a different venue.
