### ISSUE TITLE
Native SSL support for applications using Embedded jetty

### ISSUE THREAD

**Issue by pavanshankavaram** [relayrides/pushy#616]
compile 'com.turo:pushy:0.13.2'
  compile 'io.netty:netty-tcnative-boringssl-static:2.0.8.Final'
  compile 'io.netty:netty-all:4.1.25.Final'
  compile group: 'com.google.code.gson', name: 'gson', version: '2.6.2'
  compile group: 'com.eatthepath', name: 'fast-uuid', version: '0.1'

Above dependencies in build.gradle,

OS used
Windows 10, Oracle JDK 8

Openssl version :
OpenSSL 1.0.2g  1 Mar 2016

Error: javax.net.ssl.SSLHandshakeException: OPENSSL_internal:WRONG_VERSION_NUMBER

**Comment by pavanshankavaram** [comment]
Stacktrace 

javax.net.ssl.SSLHandshakeException: error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER\r\n\tat i.n.h.ssl.ReferenceCountedOpenSslEngine.sslReadErrorResult(ReferenceCountedOpenSslEngine.java:1106)\r\n\tat i.n.h.ssl.ReferenceCountedOpenSslEngine.unwrap(ReferenceCountedOpenSslEngine.java:1066)\r\n\tat i.n.h.ssl.ReferenceCountedOpenSslEngine.unwrap(ReferenceCountedOpenSslEngine.java:1132)\r\n\tat i.n.h.ssl.ReferenceCountedOpenSslEngine.unwrap(ReferenceCountedOpenSslEngine.java:1175)\r\n\tat i.n.h.ssl.SslHandler$SslEngineType$1.unwrap(SslHandler.java:216)\r\n\tat io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1275)\r\n\tat io.netty.handler.ssl.SslHandler.decodeNonJdkCompatible(SslHandler.java:1189)\r\n\tat io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1223)\r\n\tat i.n.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)\r\n\tat i.n.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428)\r\n\tat i.n.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)\r\n\tat i.n.c.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)\r\n\tat i.n.c.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)\r\n\tat i.n.c.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)\r\n\tat i.n.c.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)\r\n\tat i.n.c.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)\r\n\tat i.n.c.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)\r\n\tat io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)\r\n\tat i.n.c.n.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)\r\n\tat io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:647)\r\n\tat io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:582)\r\n\tat io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:499)\r\n\tat io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:461)\r\n\tat i.n.u.c.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)\r\n\tat i.n.u.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)\r\n\tat java.lang.Thread.run(Unknown Source)\r\n

**Comment by jchambers** [comment]
Hello!

This sounds more like a request for general support with your specific configuration than it does like a bug report or a feature request. We generally ask people to move these kinds of questions to [the Pushy mailing list](https://groups.google.com/d/forum/pushy-apns) because:

1. The mailing list has a wider audience, and you're more likely to find somebody who has experience with your particular circumstances on the mailing list.
2. Posting your question to the mailing list can help other people who are having the same problem.
3. Because there isn't a bug to fix or a feature to add, we can't reasonably solve your problem by making any kind of engineering change.

I emphasize that we'd be happy to help, but let's move this conversation to a different venue.

In the meantime:

- If you're using gradle, you do not need to specify all of Pushy's dependencies explicitly. Gradle will take care of that for you, and that also eliminates the risk of dependency version mismatches.
- As of Pushy v.0.13.2, you _do not need netty-tcnative_ if you're using Java 8 or newer.
- You appear to be using both netty-tcnative-boringssl-static (which includes its own copy of boringssl), and so the system version of OpenSSL shouldn't matter.

Try reducing your dependency list to just: `compile 'com.turo:pushy:0.13.2'`.

In any case, I'm going to close this issue for now. If you need additional support, please do send a message to the mailing list.
