### ISSUE TITLE
How to know ApnsClient is ceonnected to APNS?

### ISSUE THREAD

**Issue by zhoubo2015** [relayrides/pushy#627]
final ApnsClient apnsClient = new ApnsClientBuilder()
        .setApnsServer(ApnsClientBuilder.DEVELOPMENT_APNS_HOST)
        .setClientCredentials(new File("/path/to/certificate.p12"), "p12-file-password")
        .build();

Have some callback tell me is already connected to APNS??

**Comment by jchambers** [comment]
Hello!

This sounds more like a request for general support than it does like a bug report or a feature request. We generally ask people to move these kinds of questions to [the Pushy mailing list](https://groups.google.com/d/forum/pushy-apns) because:

1. The mailing list has a wider audience, and you're more likely to find somebody who has experience with your particular circumstances on the mailing list.
2. Posting your question to the mailing list can help other people who are having the same problem.
3. Because there isn't a bug to fix or a feature to add, we can't reasonably solve your problem by making any kind of engineering change.

I emphasize that we'd be happy to help, but let's move this conversation to a different venue.

In the meantime, please see the [`ApnsClient` documentation](http://relayrides.github.io/pushy/apidocs/0.13/com/turo/pushy/apns/ApnsClient.html), which says (in part):

> Clients maintain their own internal connection pools and open connections to the APNs server on demand. As a result, clients do not need to be "started" explicitly, and are ready to begin sending notifications as soon as they're constructed.

So, no, there isn't a way (or a need) to check whether a client is "connected."

**Comment by zhoubo2015** [comment]
OK.
