### ISSUE TITLE
Can get invalid token to the APNS server？

### ISSUE THREAD

**Issue by zhoubo2015** [relayrides/pushy#629]
APNS： feedback.sandbox.push.apple.com
              feedback.push.apple.com

**Comment by jchambers** [comment]
I'm sorry; I'm not sure what you're asking. Can you please elaborate?

Also, please note that the "feedback service" (the two servers you mentioned) are part of a much older version of the APNs protocol, and Pushy hasn't used them in years.

**Comment by zhoubo2015** [comment]
so，How do I know that the push message arrives at the iPhone?

**Comment by jchambers** [comment]
It sounds like this isn't a bug report or a feature request, but a request for general support. As [I asked you before](https://github.com/relayrides/pushy/issues/627#issuecomment-402715622), please send these kinds of requests to the [mailing list](https://groups.google.com/d/forum/pushy-apns) instead of opening issues.

I'll make an attempt at answering here, but in the future, I will insist upon moving these discussions to the mailing list. APNs, as a protocol, does not provide any mechanism to tell us whether a push notification reached its destination. It _will_ tell us if a notification was accepted by the APNs server, though; if the notification is accepted, the server will try to deliver the notification to its destination, but it makes no guarantees and offers no way of telling us what ultimately happened. That information is provided in the [`PushNotificationResponse`](http://relayrides.github.io/pushy/apidocs/0.13/com/turo/pushy/apns/PushNotificationResponse.html) that comes from the `Future` returned by the [`ApnsClient#sendNotification`](http://relayrides.github.io/pushy/apidocs/0.13/com/turo/pushy/apns/ApnsClient.html#sendNotification-T-) method.

**Comment by zhoubo2015** [comment]
Thank you.
