### ISSUE TITLE
Sending Mock APNS on AWS EC2. 

### ISSUE THREAD

**Issue by icyield** [relayrides/pushy#646]
I'm trying to run a mock apns server to ensure that our setup (not just pushy) has good throughput. 
The mock service is on AWS EC2 and behind a load balancer. It works with curl command and simple go apns2 program. These make a direct h2 connection, but pushy is getting stuck at the load balancer. Can I get pushy to make a direct h2 connection?

Pushy seems to be negotiating a connection by using the load balancer hostname (which I did not tell it!) to get access to the former apple hostname I replaced with pushproxy2.mycompany.com. Note maybe this would be solved if I could add an SSL certificate to the pushproxy-XXXXXXX.eu-west-2.elb.amazonaws.com, but AWS does not allow that.  

```
https 2018-10-12T11:54:12.978865Z app/pushproxy/7ba468ea0d0278b2 5.8.10.202:53342 - -1 -1 -1 400 - 18 288 "GET https://pushproxy-XXXXXXX.eu-west-2.elb.amazonaws.com:443/ HTTP/1.1" "-" ECDHE-RSA-AES128-GCM-SHA256 TLSv1.2 - "-" "pushproxy2.mycompany.com" "arn:aws:acm:eu-west-2:914858662894:certificate/a0558a06-f82f-4998-ac3d-20c8a9252c43" - 2018-10-12T11:54:12.978000Z "-" "-"
```

The curl and go versions make a direct h2 connection.

```
h2 2018-10-12T10:46:25.648525Z app/pushproxy/7ba468ea0d0278b2 86.172.16.230:64407 172.31.27.35:443 0.180 0.001 0.000 200 200 239 78 "POST https://pushproxy2.mycompany.com:443/3/device/a9001c6cbf953a9b2820f4da9c7f8d37e84338460304a2ce0a04a32e85ca2532 HTTP/2.0" "curl/7.61.1" ECDHE-RSA-AES128-GCM-SHA256 TLSv1.2 arn:aws:elasticloadbalancing:eu-
```

**Comment by jchambers** [comment]
Hello!

This sounds more like a request for general support than it does like a bug report or a feature request. We generally ask people to move these kinds of questions to [the Pushy mailing list](https://groups.google.com/d/forum/pushy-apns) because:

1. The mailing list has a wider audience, and you're more likely to find somebody who has experience with your particular circumstances on the mailing list.
2. Posting your question to the mailing list can help other people who are having the same problem.
3. Because there isn't a bug to fix or a feature to add, we can't reasonably solve your problem by making any kind of engineering change.

I emphasize that we'd be happy to help, but let's move this conversation to a different venue.
