### ISSUE TITLE
Pushy support for Feedback inactive devices (Apple Feedback Service) 

### ISSUE THREAD

**Issue by rohitsahay2000** [relayrides/pushy#648]
How do i get feedback inactive devices (Apple Feedback Service) , Couldn't find it in latest pushy docs.

**Comment by jchambers** [comment]
Hello!

This sounds more like a request for general support than it does like a bug report or a feature request. We generally ask people to move these kinds of questions to [the Pushy mailing list](https://groups.google.com/d/forum/pushy-apns) because:

1. The mailing list has a wider audience, and you're more likely to find somebody who has experience with your particular circumstances on the mailing list.
2. Posting your question to the mailing list can help other people who are having the same problem.
3. Because there isn't a bug to fix or a feature to add, we can't reasonably solve your problem by making any kind of engineering change.

I emphasize that we'd be happy to help, but let's move this conversation to a different venue.

In the meantime, please note that the current HTTP/2 APNs API (which is what Pushy has used since v0.5, released in January 2016) _does not have a feedback service_. The server replies to each notification individually, providing immediate feedback.
