### ISSUE TITLE
few questions: upgrading from 0.3 to 0.13.7 (yes 0.3)

### ISSUE THREAD

**Issue by guykatz** [relayrides/pushy#677]
hi all
so after a few years of using 0.3 version its time for an overhaul and I am upgrading to 0.13.7
I have a few questions I need some help with...
1. my old code had logic for retrieving expired tokens via pushManager.getExpiredTokens() and from the handleRejectedNotification's RejectedNotificationReason object.
do I understand correctly that, in the latest version, the way to deduct if a token has expired, when using synchronous notification sending (not via listeners) is when the PushNotificationResponse object is NOT accepted (!pushNotificationResponse.isAccepted()) AND has an invalidation timestamp (pushNotificationResponse.getTokenInvalidationTimestamp() != null)? is this correct?
2. my old code had a FailedConnectionListener in order to log that SSL cert is probably expired (by checking for a SSLHandshakeException cause). I could not find a way to do that in the latest version. is there some replacement or is my code not needed? (I dont have any logic on this just prints so maybe use a matrix listener?)
3. when closing the APNS client docs state "some notifications passed to sendNotification(ApnsPushNotification) may still be enqueued and not yet sent by the time the shutdown process begins; the Futures associated with those notifications will fail"
is there a way to wait for those notifications before initiating the shutdown? I see my old code checked pushManager.getQueue() in order to get the status of such notifications (i assume). anything that I can do in the latest version?
thanks for the answers, BTW, tried to backtrack all the release notes but I was not able to solve it that way, probably missed some stuff along the way.
thanks,

**Comment by jchambers** [comment]
Hello, and welcome to the future!

We'd be happy to help you with all of these questions, but because they're requests for support (and not something we can address by making any kind of engineering change), would you mind moving this discussion to [the Pushy mailing list](https://groups.google.com/d/forum/pushy-apns)? You can literally just copy/paste the text of this issue to the mailing list and we'll answer there.

In the meantime, I updated our [FAQ](https://github.com/relayrides/pushy/wiki/Frequently-asked-questions) to cover your first question about the feedback service, since that's come up a few times now.

Cheers!
