### ISSUE TITLE
failed to get ApnsClient

### ISSUE THREAD

**Issue by xmxu910506** [relayrides/pushy#695]
![111](https://user-images.githubusercontent.com/43606524/56877252-38550e80-6a7f-11e9-85cd-c6b5a751d4e4.png)

This problem occurred when APNSclient was acquired. The version information is as follows：
pushy-0.13.7
netty 4.1.32
netty-tcnative-boringssl-static 2.0.20

**Comment by jchambers** [comment]
Hello!

From the attached photograph of your monitor, it's not obvious to me that anything actually went wrong. Other than the DNS warnings, did anything bad actually happen? What happens if you try to send a notification?

Regarding the DNS warning, it appears that something somewhere is misconfigured. This is not a problem that's specific to—or caused by—Pushy.

All that said, I really don't think this is likely to be a problem with Pushy itself, and so this sounds more like a request for general support than it does like a bug report or a feature request. We generally ask people to move these kinds of questions to [the Pushy mailing list](https://groups.google.com/d/forum/pushy-apns) because:

1. The mailing list has a wider audience, and you're more likely to find somebody who has experience with your particular circumstances on the mailing list.
2. Posting your question to the mailing list can help other people who are having the same problem.
3. Because there isn't a bug to fix or a feature to add, we can't reasonably solve your problem by making any kind of engineering change.

I emphasize that we'd be happy to help, but let's move this conversation to a different venue. Thanks!

Also, going forward, please copy/paste text if you need to share error messages/stack traces instead of attaching a photo of your monitor or a screenshot. Thank you.
