### ISSUE TITLE
image rich notification sending?

### ISSUE THREAD

**Issue by deflorilemarului** [relayrides/pushy#705]
Im already using this lib to send simple text push notifs.

can I send push notifs to ios containing an image ( icon ) on the right side like recent apps do ? 
havent seen if that is possible with this lib. I saw somethign about an image but that is used when the notif is tapped.

I would like to give it an URL and ios user will see the image ( thumbnail ) when he get the notif. 
Possible ? and how can be done with this lib ?

thanks.

**Comment by jchambers** [comment]
Hello!

This sounds more like a request for general support than it does like a bug report or a feature request. We generally ask people to move these kinds of questions to [the Pushy mailing list](https://groups.google.com/d/forum/pushy-apns) because:

1. The mailing list has a wider audience, and you're more likely to find somebody who has experience with your particular circumstances on the mailing list.
2. Posting your question to the mailing list can help other people who are having the same problem.
3. Because there isn't a bug to fix or a feature to add, we can't reasonably solve your problem by making any kind of engineering change.

That said, I'm fairly certainly that there isn't an affordance in the APNs API itself for doing what you want to do. Instead, you'd send a push notification with the [mutable content](http://relayrides.github.io/pushy/apidocs/0.13/com/turo/pushy/apns/util/ApnsPayloadBuilder.html#setMutableContent(boolean)) flag, and then it would be up to the receiving app to add the image.
