### ISSUE TITLE
Why do you need topic when using collapseId? Where does topic get from?

### ISSUE THREAD

**Issue by HELLOYUANJIE** [relayrides/pushy#707]
Topic disallowed

![image](https://user-images.githubusercontent.com/34395444/60405072-9669b380-9be0-11e9-8160-03c973dbeb1f.png)

**Comment by jchambers** [comment]
Hello!

This sounds more like a request for general support than it does like a bug report or a feature request. We generally ask people to move these kinds of questions to [the Pushy mailing list](https://groups.google.com/d/forum/pushy-apns) because:

1. The mailing list has a wider audience, and you're more likely to find somebody who has experience with your particular circumstances on the mailing list.
2. Posting your question to the mailing list can help other people who are having the same problem.
3. Because there isn't a bug to fix or a feature to add, we can't reasonably solve your problem by making any kind of engineering change.

I emphasize that we'd be happy to help, but let's move this conversation to a different venue.
