### ISSUE TITLE
Tried to mark promise as 'failed',but it was already done

### ISSUE THREAD

**Issue by xmxu910506** [relayrides/pushy#710]
![01](https://user-images.githubusercontent.com/43606524/61447134-f3a48980-a982-11e9-9740-7446f3efd456.png)

![02](https://user-images.githubusercontent.com/43606524/61447254-2a7a9f80-a983-11e9-8eb8-83813c89d33c.png)

**Comment by jchambers** [comment]
Respectfully, there isn't enough information here to figure out what's going wrong. How often does this happen? What were you trying to do when it happened? Do you think this is the same issue as #693?

Also, as I have asked you before: please do not post photographs of your monitor as the main content of a bug report. Even in the best of circumstances, posting a stack trace without additional explanation/context is usually not enough for us to figure out what's going on. Posting it as a photograph makes things even harder because the text is often harder to read and isn't searchable.

**Comment by jchambers** [comment]
Closing due to lack of information. @xmxu910506 if you have an opportunity to provide more information, we'll happily revisit the issue.
