### ISSUE TITLE
Question: how to check a certificate if ApnsClient.connect is unavailable

### ISSUE THREAD

**Issue by kas-kad** [relayrides/pushy#721]
Our application is a Push Gateway, we provide Push functionality to our customers, which means we have to use different APNS certificates for different connections, therefore one of the main requirement for our application is to validate arbitrary certificates provided by customers and fail fast if the cert is inappropriate. We've been using Pushy 0.9 for a long time. Our approach to validate the APNS certificates was based on using `ApnsClient.connect()` method: before accepting the certificate from customer, we try to `connect` with it first. In case of successful connect, we accept the certificate with the full confidence it is a valid one. Now, in recent versions of Pushy, this `ApnsClient.connect` API was removed and I wonder if there is a similar way to validate an arbitrary certificate **before** any notification sending attempts?

**Comment by jchambers** [comment]
Hello!

This sounds more like a request for general support than it does like a bug report or a feature request. We generally ask people to move these kinds of questions to [the Pushy mailing list](https://groups.google.com/d/forum/pushy-apns) because:

1. The mailing list has a wider audience, and you're more likely to find somebody who has experience with your particular circumstances on the mailing list.
2. Posting your question to the mailing list can help other people who are having the same problem.
3. Because there isn't a bug to fix or a feature to add, we can't reasonably solve your problem by making any kind of engineering change.

I emphasize that we'd be happy to help, but let's move this conversation to a different venue.
