### ISSUE TITLE
io.netty.channel.ChannelException: Unable to create Channel from class class io.netty.channel.socket.nio.NioSocketChannel

### ISSUE THREAD

**Issue by PaulDaviesC** [relayrides/pushy#729]
While I am trying to `sendNotificationFuture.get()` as mentioned in the doc I am getting `io.netty.channel.ChannelException: Unable to create Channel from class class io.netty.channel.socket.nio.NioSocketChannel`. 

This problem we were facing only on our EC2 instances. Locally, when I test it out in my Mac, I am not facing any issue. I also see the client goes in to shutdown right after this error, automatically. Can someone point out what could be the issue?

**Comment by jchambers** [comment]
This sounds like some kind of dependency issue. I don't think this is a problem we can solve within Pushy itself. You might try the [mailing list](https://groups.google.com/d/forum/pushy-apns), though.

I'm going to close this issue for now because I don't believe there's any change we can make to resolve this problem for you. If you do uncover new information that points to a bug within Pushy, please let us know and we'll happily revisit the issue.
