### ISSUE TITLE
Tomcat Memory Leaks on netty

### ISSUE THREAD

**Issue by patrixgdd** [relayrides/pushy#73]
hi,

I think this is what I did very similar to this thread:
https://github.com/relayrides/pushy/issues/29

On the current pushy 0.3, it is Spring 4.0 using Tomcat 7.0.53 with jdk1.7.0_55 x64.
Already put Thread.sleep(2000) after pushManager.shutdown():

```
INFO: Push manager shutting down.
Apr 21, 2014 11:50:40 AM org.apache.catalina.loader.WebappClassLoader checkThreadLocalMapForLeaks
SEVERE: The web application [/xxxapps] created a ThreadLocal with key of type [io.netty.channel.ChannelHandlerAdapter$1] (value [io.netty.channel.ChannelHandlerAdapter$1@52d67995]) and a value of type [java.util.WeakHashMap] (value [{class com.relayrides.pushy.apns.ApnsConnection$1=true}]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
Apr 21, 2014 11:50:40 AM org.apache.catalina.loader.WebappClassLoader checkThreadLocalMapForLeaks
SEVERE: The web application [/xxxapps] created a ThreadLocal with key of type [io.netty.util.internal.ThreadLocalRandom$2] (value [io.netty.util.internal.ThreadLocalRandom$2@7ec84faf]) and a value of type [io.netty.util.internal.ThreadLocalRandom] (value [io.netty.util.internal.ThreadLocalRandom@10e7ab30]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
Apr 21, 2014 11:50:40 AM org.apache.catalina.loader.WebappClassLoader checkThreadLocalMapForLeaks
SEVERE: The web application [/xxxapps] created a ThreadLocal with key of type [io.netty.util.Recycler$1] (value [io.netty.util.Recycler$1@5997e4fb]) and a value of type [io.netty.util.Recycler.Stack] (value [io.netty.util.Recycler$Stack@33a48b1]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
```

Tried several times with the same SEVERE memory leek alerts there.

I thought it could be harmless, but I am not familiar with netty framework. I have to make sure otherwise I need to restart tomcat.

Any suggestions?
I would see if there is a listener to remove the netty from the Tomcat context (eg. on web.xml).

Many Thanks

**Comment by Pereitor** [comment]
Hi,

It's been 3 years. I just started using Pushy in my web project and I'm worried about the possible consequences. Is there any news regarding this issue?

**Comment by jchambers** [comment]
Please see https://github.com/relayrides/pushy/wiki/Using-Pushy-in-an-application-container#general-issues. The issues remain, but are not an issue in steady-state operation.

**Comment by Pereitor** [comment]
Thanks a lot for your feedback, jchambers. Anyway, I'm concerned by any possible memory leaks or unstable behaviour that this issue might cause. I'll try to figure out a way of tracking these threads and stopping them when instances are closed, anyway.

**Comment by jchambers** [comment]
> Anyway, I'm concerned by any possible memory leaks or unstable behaviour that this issue might cause.

Please do as you see fit, but for other readers, I want to be clear that this is not a stability issue, nor does it lead to "leaks" in any conventional sense. Tomcat, by design, clears up any lingering `ThreadLocal` instances. It will still issue a warning, but there is no reason to believe there are actual adverse effects.

**Comment by christophmegusta** [comment]
its closed now though i want to add my opinion on documentation.
this "problem" gets far to much attention in the README. our technical management has tendency to read only headlines and decline to use this library just because they read "memory leaks". they dont read this ticket and "trust" what they read on readme. i had to do hours of explaining why this "problem" is absolutely no reason for any worries to runtime stability.
i dont say hide the warning, but maybe make it less agressive.
