### ISSUE TITLE
Mock server requires HTTP2+TLS with prior knowledge

### ISSUE THREAD

**Issue by pertu** [relayrides/pushy#736]
### Problem
Cannot connect to APNS mock server using Java 11's http client

### Details
Apple's APNS endpoint is OK with HTTP2 prior knowledge:
```shell
$ curl --http2-prior-knowledge https://api.sandbox.push.apple.com
{"reason":"MethodNotAllowed"}%
```
And *without* prior knowledge:
```shell
$ curl https://api.sandbox.push.apple.com
{"reason":"MethodNotAllowed"}%
```

Pushy APNS mock server is OK with HTTP2 prior knowledge:
```shell
$ curl --insecure --http2-prior-knowledge https://localhost:6060
{"reason":"InternalServerError"}%
```
But does not support connections without it:
```shell
$ curl --insecure --silent https://localhost:6060 | hexdump -C
00000000  00 00 0c 04 00 00 00 00  00 00 03 00 00 05 dc 00  |................|
00000010  06 00 00 20 00 00 00 2b  07 00 00 00 00 00 00 00  |... ...+........|
00000020  00 00 00 00 00 01 55 6e  65 78 70 65 63 74 65 64  |......Unexpected|
00000030  20 48 54 54 50 2f 31 2e  78 20 72 65 71 75 65 73  | HTTP/1.x reques|
00000040  74 3a 20 47 45 54 20 2f  20                       |t: GET / |
```

It may be a problem with HTTP clients (such as Java 11's ~~new~~ http client) which do not support explicit HTTP2-only setting.

Also, [HTTP2 specification](https://http2.github.io/http2-spec/#discover-https) *requires* TLS-based connections to use [TLS-ALPN](https://tools.ietf.org/html/rfc7301) protocol negotiation (no HTTP2 prior knowledge).

**Comment by jchambers** [comment]
Seems legit. I'll have to do some research to better understand the space.

To manage expectations, while making Pushy's mock server as accurate as possible for third-party clients is a goal, it's not the _first_ goal, and this may get prioritized accordingly. A pull request would certainly be welcome in this case!

**Comment by jchambers** [comment]
@pertu Looking at this more closely, is this just a matter of calling [`MockApnsServerBuilder.html#setUseAlpn(true)`](https://pushy-apns.org/apidocs/0.13/com/turo/pushy/apns/server/MockApnsServerBuilder.html#setUseAlpn(boolean))?

We made ALPN optional on the server because older versions of Java don't support it natively and getting ALPN support in place required a lot of hoop-jumping on the part of Pushy users and generated a lot of support requests. It's still there for folks who want it, though. Does that do what you need?

**Comment by jchambers** [comment]
@pertu I realize that "sit on an issue for more than a month then close it after two days" isn't the best pattern, but I'm 99% sure from your test cases that `setUseAlpn` is the missing piece here. Since this is a thing Pushy already supports and there isn't any action to be taken, I'm going to close this issue for now. If I'm misunderstanding the problem, please let me know and I'll reopen this immediately.

Thanks!
